import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Borroq - Boar Skinchanger': {
    name: 'Borroq - Boar Skinchanger',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-borroq-bs.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-borroq-bs-back.png',
  },
  'Cave Dweller Alpha': {
    name: 'Cave Dweller Alpha',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-cave-dweller-alpha.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-cave-dweller-alpha-back.png',
  },
  'Champion Of Bone': {
    name: 'Champion Of Bone',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-champion-of-bone.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-champion-of-bone-back.png',
  },
  'Chosen Of Styr': {
    name: 'Chosen Of Styr',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-chosen-of-styr.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-chosen-of-styr-back.png',
  },
  'Harma - The Dogshead': {
    name: 'Harma - The Dogshead',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harma-td.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harma-td-back.png',
  },
  'Harma - Vanguard Commander': {
    name: 'Harma - Vanguard Commander',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harma-vc.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harma-vc-back.png',
    isCommander: true,
  },
  "Harma's Bannerman": {
    name: "Harma's Bannerman",
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harmas-bannerman.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harmas-bannerman-back.png',
  },
  'Jarl - Advance Raid Leader': {
    name: 'Jarl - Advance Raid Leader',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-jarl-arl.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-jarl-arl-back.png',
  },
  'Jon Snow - The Crow-Come-Over': {
    name: 'Jon Snow - The Crow-Come-Over',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-jon-snow-tcco.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-jon-snow-tcco-back.png',
  },
  'Chieftain Of The Giants': {
    name: 'Chieftain Of The Giants',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-cotg.png',
    imageUrlBack: '',
    isCommander: true,
  },
  'Mance Rayder - King Beyond The Wall': {
    name: 'Mance Rayder - King Beyond The Wall',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mance-rayder-kbtw.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mance-rayder-kbtw-back.png',
    isCommander: true,
  },
  'Raid Leader': {
    name: 'Raid Leader',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-raid-leader.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-raid-leader-back.png',
  },
  'Rattleshirt - Ruthless Slaughterer': {
    name: 'Rattleshirt - Ruthless Slaughterer',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-rattleshirt-rs.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-rattleshirt-rs-back.png',
  },
  'Rattleshirt - The Lord Of Bones': {
    name: 'Rattleshirt - The Lord Of Bones',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-rattleshirt-tlob.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-rattleshirt-tlob-back.png',
    isCommander: true,
  },
  Skinchanger: {
    name: 'Skinchanger',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-skinchanger.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-skinchanger-back.png',
  },
  'Spearwife Matriarch': {
    name: 'Spearwife Matriarch',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-spearwife-matriarch.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-spearwife-matriarch-back.png',
  },
  'Styr - Magnar Of Thenn': {
    name: 'Styr - Magnar Of Thenn',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-styr-mot.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-styr-mot-back.png',
    isCommander: true,
  },
  'The Great Walrus - Lord Of The Frozen Shore': {
    name: 'The Great Walrus - Lord Of The Frozen Shore',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-great-walrus-lotfs.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-great-walrus-lotfs-back.png',
    isCommander: true,
  },
  'The Great Walrus - Steeled Through Ice And Snow': {
    name: 'The Great Walrus - Steeled Through Ice And Snow',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-great-walrus-stias.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-great-walrus-stias-back.png',
  },
  'The Weeper - Cruel Tyrant': {
    name: 'The Weeper - Cruel Tyrant',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-weeper-ct.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-weeper-ct-back.png',
  },
  'The Weeper - Horrific Butcher': {
    name: 'The Weeper - Horrific Butcher',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-weeper-hb.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-weeper-hb-back.png',
    isCommander: true,
  },
  'Tormund Giantsbane - Tall-Talker, Horn-Blower, Breaker Of Ice': {
    name: 'Tormund Giantsbane - Tall-Talker, Horn-Blower, Breaker Of Ice',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-tormund-giantsbane-tthbboi.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-tormund-giantsbane-tthbboi-back.png',
  },
  'Tormund Giantsbane - Thunderfist': {
    name: 'Tormund Giantsbane - Thunderfist',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-tormund-giantsbane-t.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-tormund-giantsbane-t-back.png',
    isCommander: true,
  },
  'Varamyr Sixskins': {
    name: 'Varamyr Sixskins',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-varamyr-sixskins-ms-rules.png',
    imageUrlBack: '',
    isCommander: true,
  },
  'Walrus Clan Chieftain': {
    name: 'Walrus Clan Chieftain',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-walrus-clan-chieftain.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-walrus-clan-chieftain-back.png',
  },
  'Ygritte - Spearwife Archer': {
    name: 'Ygritte - Spearwife Archer',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-ygritte-sa.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-ygritte-sa-back.png',
  },
};

export default cardData;
