import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Regroup and Reform': {
    name: 'Regroup and Reform',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-t1.png',
    imageUrlBack: '',
  },
  'Coordination Tactics - Freefolk': {
    name: 'Coordination Tactics - Freefolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-t2.png',
    imageUrlBack: '',
  },
  "There's Too Many!": {
    name: "There's Too Many!",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-t3.png',
    imageUrlBack: '',
  },
  'Diversion Tactics - Freefolk': {
    name: 'Diversion Tactics - Freefolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-t4.png',
    imageUrlBack: '',
  },
  'Overwhelming Assault': {
    name: 'Overwhelming Assault',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-t5.png',
    imageUrlBack: '',
  },
  'Surrounded and Exposed': {
    name: 'Surrounded and Exposed',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-t6.png',
    imageUrlBack: '',
  },
  'The Endless Horde': {
    name: 'The Endless Horde',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-t7.png',
    imageUrlBack: '',
  },
  'Rush of Aggression - Tormund Giantsbane': {
    name: 'Rush of Aggression - Tormund Giantsbane',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-tormund-giantsbane-t-t1.png',
    imageUrlBack: '',
  },
  'Counter Assault': {
    name: 'Counter Assault',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-tormund-giantsbane-t-t2.png',
    imageUrlBack: '',
  },
  'Devastating Impact - Tormund Giantsbane': {
    name: 'Devastating Impact - Tormund Giantsbane',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-tormund-giantsbane-t-t3.png',
    imageUrlBack: '',
  },
  'Final Strike - Styr': {
    name: 'Final Strike - Styr',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-styr-mot-t1.png',
    imageUrlBack: '',
  },
  'Thenn Defiance': {
    name: 'Thenn Defiance',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-styr-mot-t2.png',
    imageUrlBack: '',
  },
  "Styr's Vengeance": {
    name: "Styr's Vengeance",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-styr-mot-t3.png',
    imageUrlBack: '',
  },
  'Cruel Methods - The Weeper': {
    name: 'Cruel Methods - The Weeper',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-weeper-hb-t1.png',
    imageUrlBack: '',
  },
  'Price of Failure - The Weeper': {
    name: 'Price of Failure - The Weeper',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-weeper-hb-t2.png',
    imageUrlBack: '',
  },
  'Remorseless Examples - The Weeper': {
    name: 'Remorseless Examples - The Weeper',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-weeper-hb-t3.png',
    imageUrlBack: '',
  },
  'Hit and Run - Harma': {
    name: 'Hit and Run - Harma',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harma-vc-t1.png',
    imageUrlBack: '',
  },
  'Feinting Maneuver': {
    name: 'Feinting Maneuver',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harma-vc-t2.png',
    imageUrlBack: '',
  },
  'Swift Reposition - Harma': {
    name: 'Swift Reposition - Harma',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-harma-vc-t3.png',
    imageUrlBack: '',
  },
  'Bloody Trophies': {
    name: 'Bloody Trophies',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-rattleshirt-tlob-t1.png',
    imageUrlBack: '',
  },
  'Weapon Trophies': {
    name: 'Weapon Trophies',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-rattleshirt-tlob-t2.png',
    imageUrlBack: '',
  },
  'Armor Trophies': {
    name: 'Armor Trophies',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-rattleshirt-tlob-t3.png',
    imageUrlBack: '',
  },
  'Wildling Diplomacy': {
    name: 'Wildling Diplomacy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mance-rayder-kbtw-t1.png',
    imageUrlBack: '',
  },
  'Predictable Maneuvers - Mance Rayder': {
    name: 'Predictable Maneuvers - Mance Rayder',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mance-rayder-kbtw-t2.png',
    imageUrlBack: '',
  },
  'The Long Plan': {
    name: 'The Long Plan',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mance-rayder-kbtw-t3.png',
    imageUrlBack: '',
  },
  'Shrug It Off': {
    name: 'Shrug It Off',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t1.png',
    imageUrlBack: '',
  },
  Trample: {
    name: 'Trample',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t2.png',
    imageUrlBack: '',
  },
  Enrage: {
    name: 'Enrage',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t3.png',
    imageUrlBack: '',
  },
  "Chieftain's Orders": {
    name: "Chieftain's Orders",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t4.png',
    imageUrlBack: '',
  },
  'Monsters From The North': {
    name: 'Monsters From The North',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t5.png',
    imageUrlBack: '',
  },
  'Last Of Their Kind': {
    name: 'Last Of Their Kind',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t6.png',
    imageUrlBack: '',
  },
  'Defiant Roar': {
    name: 'Defiant Roar',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t7.png',
    imageUrlBack: '',
  },
  'Hurl Boulder': {
    name: 'Hurl Boulder',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t8.png',
    imageUrlBack: '',
  },
  'Overrun - Mag The Mighty': {
    name: 'Overrun - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t9.png',
    imageUrlBack: '',
  },
  Blitz: {
    name: 'Blitz',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-mag-the-mighty-t10.png',
    imageUrlBack: '',
  },
  'Battle Endurance - The Great Walrus': {
    name: 'Battle Endurance - The Great Walrus',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-great-walrus-lotfs-t1.png',
    imageUrlBack: '',
  },
  'Frozen Shore Resilience': {
    name: 'Frozen Shore Resilience',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-great-walrus-lotfs-t2.png',
    imageUrlBack: '',
  },
  "Walrus' Strength": {
    name: "Walrus' Strength",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-the-great-walrus-lotfs-t3.png',
    imageUrlBack: '',
  },
  'Bonded Guardians': {
    name: 'Bonded Guardians',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-varamyr-sixskins-ms-t1.png',
    imageUrlBack: '',
  },
  'Bonded Command': {
    name: 'Bonded Command',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-varamyr-sixskins-ms-t2.png',
    imageUrlBack: '',
  },
  'Summon Companions': {
    name: 'Summon Companions',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ff-varamyr-sixskins-ms-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
