import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Regroup and Reform - Freefolk': {
    name: 'Regroup and Reform - Freefolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-t1.png',
    imageUrlBack: '',
  },
  'Coordination Tactics - Freefolk': {
    name: 'Coordination Tactics - Freefolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-t2.png',
    imageUrlBack: '',
  },
  "There's Too Many! - Freefolk": {
    name: "There's Too Many! - Freefolk",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-t3.png',
    imageUrlBack: '',
  },
  'Diversion Tactics - Freefolk': {
    name: 'Diversion Tactics - Freefolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-t4.png',
    imageUrlBack: '',
  },
  'Overwhelming Assault - Freefolk': {
    name: 'Overwhelming Assault - Freefolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-t5.png',
    imageUrlBack: '',
  },
  'Surrounded and Exposed - Freefolk': {
    name: 'Surrounded and Exposed - Freefolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-t6.png',
    imageUrlBack: '',
  },
  'The Endless Horde - Freefolk': {
    name: 'The Endless Horde - Freefolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-t7.png',
    imageUrlBack: '',
  },
  'Rush of Aggression - Tormund Giantsbane': {
    name: 'Rush of Aggression - Tormund Giantsbane',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-tormund-giantsbane-t-t1.png',
    imageUrlBack: '',
  },
  'Counter Assault - Tormund Giantsbane': {
    name: 'Counter Assault - Tormund Giantsbane',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-tormund-giantsbane-t-t2.png',
    imageUrlBack: '',
  },
  'Devastating Impact - Tormund Giantsbane': {
    name: 'Devastating Impact - Tormund Giantsbane',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-tormund-giantsbane-t-t3.png',
    imageUrlBack: '',
  },
  'Bitter Demise - Styr': {
    name: 'Bitter Demise - Styr',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-styr-mot-t1.png',
    imageUrlBack: '',
  },
  'Thenn Defiance - Styr': {
    name: 'Thenn Defiance - Styr',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-styr-mot-t2.png',
    imageUrlBack: '',
  },
  "Styr's Vengeance - Styr": {
    name: "Styr's Vengeance - Styr",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-styr-mot-t3.png',
    imageUrlBack: '',
  },
  'Cruel Methods - The Weeper': {
    name: 'Cruel Methods - The Weeper',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-the-weeper-hb-t1.png',
    imageUrlBack: '',
  },
  'Price of Failure - The Weeper': {
    name: 'Price of Failure - The Weeper',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-the-weeper-hb-t2.png',
    imageUrlBack: '',
  },
  'Remorseless Examples - The Weeper': {
    name: 'Remorseless Examples - The Weeper',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-the-weeper-hb-t3.png',
    imageUrlBack: '',
  },
  'Hit and Run - Harma': {
    name: 'Hit and Run - Harma',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-harma-vc-t1.png',
    imageUrlBack: '',
  },
  'Feinting Maneuver - Harma': {
    name: 'Feinting Maneuver - Harma',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-harma-vc-t2.png',
    imageUrlBack: '',
  },
  'Swift Reposition - Harma': {
    name: 'Swift Reposition - Harma',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-harma-vc-t3.png',
    imageUrlBack: '',
  },
  'Bloody Trophies - Rattleshirt': {
    name: 'Bloody Trophies - Rattleshirt',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-rattleshirt-tlob-t1.png',
    imageUrlBack: '',
  },
  'Weapon Trophies - Rattleshirt': {
    name: 'Weapon Trophies - Rattleshirt',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-rattleshirt-tlob-t2.png',
    imageUrlBack: '',
  },
  'Armor Trophies - Rattleshirt': {
    name: 'Armor Trophies - Rattleshirt',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-rattleshirt-tlob-t3.png',
    imageUrlBack: '',
  },
  'Wildling Diplomacy - Mance Rayder': {
    name: 'Wildling Diplomacy - Mance Rayder',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mance-rayder-kbtw-t1.png',
    imageUrlBack: '',
  },
  'Predictable Maneuvers - Mance Rayder': {
    name: 'Predictable Maneuvers - Mance Rayder',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mance-rayder-kbtw-t2.png',
    imageUrlBack: '',
  },
  'The Long Plan - Mance Rayder': {
    name: 'The Long Plan - Mance Rayder',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mance-rayder-kbtw-t3.png',
    imageUrlBack: '',
  },
  'Shrug It Off - Mag The Mighty': {
    name: 'Shrug It Off - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t1.png',
    imageUrlBack: '',
  },
  'Trample - Mag The Mighty': {
    name: 'Trample - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t2.png',
    imageUrlBack: '',
  },
  'Enrage - Mag The Mighty': {
    name: 'Enrage - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t3.png',
    imageUrlBack: '',
  },
  "Chieftain's Orders - Mag The Mighty": {
    name: "Chieftain's Orders - Mag The Mighty",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t4.png',
    imageUrlBack: '',
  },
  'Monsters From The North - Mag The Mighty': {
    name: 'Monsters From The North - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t5.png',
    imageUrlBack: '',
  },
  'Last Of Their Kind - Mag The Mighty': {
    name: 'Last Of Their Kind - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t6.png',
    imageUrlBack: '',
  },
  'Defiant Roar - Mag The Mighty': {
    name: 'Defiant Roar - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t7.png',
    imageUrlBack: '',
  },
  'Hurl Boulder - Mag The Mighty': {
    name: 'Hurl Boulder - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t8.png',
    imageUrlBack: '',
  },
  'Overrun - Mag The Mighty': {
    name: 'Overrun - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t9.png',
    imageUrlBack: '',
  },
  'Blitz - Mag The Mighty': {
    name: 'Blitz - Mag The Mighty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-mag-the-mighty-t10.png',
    imageUrlBack: '',
  },
  'Summon Companions - Varamyr Sixskins': {
    name: 'Summon Companions - Varamyr Sixskins',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-varamyr-sixskins-ms-t1.png',
    imageUrlBack: '',
  },
  'Bonded Guardians - Varamyr Sixskins': {
    name: 'Bonded Guardians - Varamyr Sixskins',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-varamyr-sixskins-ms-t2.png',
    imageUrlBack: '',
  },
  'Bonded Command - Varamyr Sixskins': {
    name: 'Bonded Command - Varamyr Sixskins',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-varamyr-sixskins-ms-t3.png',
    imageUrlBack: '',
  },
  'Battle Endurance - The Great Walrus': {
    name: 'Battle Endurance - The Great Walrus',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-the-great-walrus-lotfs-t1.png',
    imageUrlBack: '',
  },
  'Frozen Shore Resilience - The Great Walrus': {
    name: 'Frozen Shore Resilience - The Great Walrus',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-the-great-walrus-lotfs-t2.png',
    imageUrlBack: '',
  },
  "Walrus' Strength - The Great Walrus": {
    name: "Walrus' Strength - The Great Walrus",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/ff-the-great-walrus-lotfs-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
