import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Barristan Selmy - The Bold': {
    name: 'Barristan Selmy - The Bold',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-barristan-selmy-tb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-barristan-selmy-tb-back.png',
    isCommander: true,
  },
  'Belwas - The Strong': {
    name: 'Belwas - The Strong',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-belwas-ts.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-belwas-ts-back.png',
    isCommander: true,
  },
  'Belwas - Veteran Pit-Fighter': {
    name: 'Belwas - Veteran Pit-Fighter',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-belwas-vpf.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-belwas-vpf-back.png',
  },
  'Cohollo - Bloodrider': {
    name: 'Cohollo - Bloodrider',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-cohollo-b.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-cohollo-b-back.png',
  },
  'Daario Naharis - Stormcrow Captain (Targaryen)': {
    name: 'Daario Naharis - Stormcrow Captain (Targaryen)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daario-naharis-sc.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daario-naharis-sc-back.png',
    isCommander: true,
  },
  'Daenerys Targaryen - Mother of Dragons': {
    name: 'Daenerys Targaryen - Mother of Dragons',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-mod.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-mod-back.png',
    isCommander: true,
  },
  'Daenerys Targaryen - Queen of Meereen': {
    name: 'Daenerys Targaryen - Queen of Meereen',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-qom.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-qom-back.png',
    isCommander: true,
  },
  'Grey Worm - Freed By The Dragon': {
    name: 'Grey Worm - Freed By The Dragon',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-grey-worm-fbtd.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-grey-worm-fbtd-back.png',
  },
  'Grey Worm - Unsullied Commander': {
    name: 'Grey Worm - Unsullied Commander',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-grey-worm-uc.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-grey-worm-uc-back.png',
    isCommander: true,
  },
  'Haggo - Bloodrider': {
    name: 'Haggo - Bloodrider',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-haggo-b.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-haggo-b-back.png',
  },
  'Jorah Mormont - Penitent Betrayer': {
    name: 'Jorah Mormont - Penitent Betrayer',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-pb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-pb-back.png',
  },
  'Jorah Mormont - The Andal': {
    name: 'Jorah Mormont - The Andal',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-ta.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-ta-back.png',
  },
  'Jorah Mormont - The Exiled Knight': {
    name: 'Jorah Mormont - The Exiled Knight',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-tek.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-tek-back.png',
  },
  'Jorah Mormont - Westerosi Tactician': {
    name: 'Jorah Mormont - Westerosi Tactician',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-wt.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-wt-back.png',
    isCommander: true,
  },
  'Khal Drogo - The Great Khal': {
    name: 'Khal Drogo - The Great Khal',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-khal-drogo-tgk.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-khal-drogo-tgk-back.png',
    isCommander: true,
  },
  'Outrider Ko': {
    name: 'Outrider Ko',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-outrider-ko.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-outrider-ko-back.png',
  },
  'Qotho - Bloodrider': {
    name: 'Qotho - Bloodrider',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-qotho-b.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-qotho-b-back.png',
  },
  'Rakharo - Bloodrider': {
    name: 'Rakharo - Bloodrider',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-rakharo-b.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-rakharo-b-back.png',
  },
  'Screamer Ko': {
    name: 'Screamer Ko',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-screamer-ko.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-screamer-ko-back.png',
  },
  'Unsullied Officer': {
    name: 'Unsullied Officer',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-unsullied-officer.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-unsullied-officer-back.png',
  },
  'Stormcrow Lieutenant (Targaryen)': {
    name: 'Stormcrow Lieutenant (Targaryen)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-stormcrow-lieutenant.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-stormcrow-lieutenant-back.png',
  },
  "Marselen - Mother's Men Commander": {
    name: "Marselen - Mother's Men Commander",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-marselen-mmc.jpg',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-marselen-mmc-back.jpg',
    isCommander: true,
  },
  'Marselen - Unsullied Captain': {
    name: 'Marselen - Unsullied Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-marselen-uc.jpg',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-marselen-uc-back.jpg',
  },
  'Mirri Maz Duur - Resentful Healer': {
    name: 'Mirri Maz Duur - Resentful Healer',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-mirri-maz-duur-rh.jpg',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-mirri-maz-duur-rh-back.jpg',
  },
  'Skahaz Mo Kandaq - Merciless Ghiscari': {
    name: 'Skahaz Mo Kandaq - Merciless Ghiscari',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-skahaz-mo-kandaq-mg.jpg',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-skahaz-mo-kandaq-mg-back.jpg',
  },
  'Skahaz Mo Kandaq - The Shavepate': {
    name: 'Skahaz Mo Kandaq - The Shavepate',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-skahaz-mo-kandaq-ts.jpg',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-skahaz-mo-kandaq-ts-back.jpg',
    isCommander: true,
  },
};

export default cardData;
