import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Overrun - Targaryen': {
    name: 'Overrun - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-t1.png',
    imageUrlBack: '',
  },
  'Sudden Retreat - Targaryen': {
    name: 'Sudden Retreat - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-t2.png',
    imageUrlBack: '',
  },
  'Swift Reposition - Targaryen': {
    name: 'Swift Reposition - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-t3.png',
    imageUrlBack: '',
  },
  'Fire and Blood - Targaryen': {
    name: 'Fire and Blood - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-t4.png',
    imageUrlBack: '',
  },
  'Field Control - Targaryen': {
    name: 'Field Control - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-t5.png',
    imageUrlBack: '',
  },
  'Unstoppable Advance - Targaryen': {
    name: 'Unstoppable Advance - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-t6.png',
    imageUrlBack: '',
  },
  'Blood of the Dragon - Targaryen': {
    name: 'Blood of the Dragon - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-t7.png',
    imageUrlBack: '',
  },
  'Addrivat! - Khal Drogo': {
    name: 'Addrivat! - Khal Drogo',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-khal-drogo-tgk-t1.png',
    imageUrlBack: '',
  },
  'Lead by Example - Khal Drogo': {
    name: 'Lead by Example - Khal Drogo',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-khal-drogo-tgk-t2.png',
    imageUrlBack: '',
  },
  'Ride-By Attack - Khal Drogo': {
    name: 'Ride-By Attack - Khal Drogo',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-khal-drogo-tgk-t3.png',
    imageUrlBack: '',
  },
  'Assault Orders - Khal Drogo': {
    name: 'Assault Orders - Khal Drogo',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-khal-drogo-tgk-t4.png',
    imageUrlBack: '',
  },
  'Targaryen Supremacy - Daenerys Targaryen (Queen of Meereen)': {
    name: 'Targaryen Supremacy - Daenerys Targaryen (Queen of Meereen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-qom-t1.png',
    imageUrlBack: '',
  },
  'Counterplot - Daenerys Targaryen (Queen of Meereen)': {
    name: 'Counterplot - Daenerys Targaryen (Queen of Meereen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-qom-t2.png',
    imageUrlBack: '',
  },
  'Subjugation of Power - Daenerys Targaryen (Queen of Meereen)': {
    name: 'Subjugation of Power - Daenerys Targaryen (Queen of Meereen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-qom-t3.png',
    imageUrlBack: '',
  },
  'Remorseless Examples - Daenerys Targaryen (Queen of Meereen)': {
    name: 'Remorseless Examples - Daenerys Targaryen (Queen of Meereen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-qom-t4.png',
    imageUrlBack: '',
  },
  'Sustained Assault - Barristan Selmy': {
    name: 'Sustained Assault - Barristan Selmy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-barristan-selmy-tb-t1.png',
    imageUrlBack: '',
  },
  'Combat Prowess - Barristan Selmy': {
    name: 'Combat Prowess - Barristan Selmy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-barristan-selmy-tb-t2.png',
    imageUrlBack: '',
  },
  'Legendary Boldness - Barristan Selmy': {
    name: 'Legendary Boldness - Barristan Selmy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-barristan-selmy-tb-t3.png',
    imageUrlBack: '',
  },
  'Victory Comes Hard - Barristan Selmy': {
    name: 'Victory Comes Hard - Barristan Selmy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-barristan-selmy-tb-t4.png',
    imageUrlBack: '',
  },
  'Dracarys! - Daenerys Targaryen (Mother Of Dragons)': {
    name: 'Dracarys! - Daenerys Targaryen (Mother Of Dragons)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-mod-t1.png',
    imageUrlBack: '',
  },
  "Dragon's Flight - Daenerys Targaryen (Mother Of Dragons)": {
    name: "Dragon's Flight - Daenerys Targaryen (Mother Of Dragons)",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-mod-t2.png',
    imageUrlBack: '',
  },
  'Promise of Fire - Daenerys Targaryen (Mother Of Dragons)': {
    name: 'Promise of Fire - Daenerys Targaryen (Mother Of Dragons)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-mod-t3.png',
    imageUrlBack: '',
  },
  'Fire Made Flesh - Daenerys Targaryen (Mother Of Dragons)': {
    name: 'Fire Made Flesh - Daenerys Targaryen (Mother Of Dragons)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daenerys-targaryen-mod-t4.png',
    imageUrlBack: '',
  },
 'Issue Commands - Grey Worm': {
    name: 'Issue Commands - Grey Worm',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-grey-worm-uc-t1.png',
    imageUrlBack: '',
  },
  'Lash Out - Grey Worm': {
    name: 'Lash Out - Grey Worm',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-grey-worm-uc-t2.png',
    imageUrlBack: '',
  },
  'Battle Endurance - Grey Worm': {
    name: 'Battle Endurance - Grey Worm',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-grey-worm-uc-t3.png',
    imageUrlBack: '',
  },
  'Retribution of The Dragon - Grey Worm': {
    name: 'Retribution of The Dragon - Grey Worm',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-grey-worm-uc-t4.png',
    imageUrlBack: '',
  },
  
  'Sellsword Negotiations - Daario Naharis (Targaryen)': {
    name: 'Sellsword Negotiations - Daario Naharis (Targaryen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daario-naharis-sc-t1.png',
    imageUrlBack: '',
  },
  'Sellsword Bravado - Daario Naharis (Targaryen)': {
    name: 'Sellsword Bravado - Daario Naharis (Targaryen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daario-naharis-sc-t2.png',
    imageUrlBack: '',
  },
  'Reckless Strikes - Daario Naharis (Targaryen)': {
    name: 'Reckless Strikes - Daario Naharis (Targaryen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daario-naharis-sc-t3.png',
    imageUrlBack: '',
  },
  'Hasty Offense - Daario Naharis (Targaryen)': {
    name: 'Hasty Offense - Daario Naharis (Targaryen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-daario-naharis-sc-t4.png',
    imageUrlBack: '',
  },
  'Pathetic Attempt - Belwas': {
    name: 'Pathetic Attempt - Belwas',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-belwas-ts-t1.png',
    imageUrlBack: '',
  },
  'Expert Parry - Belwas': {
    name: 'Expert Parry - Belwas',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-belwas-ts-t2.png',
    imageUrlBack: '',
  },
  'Good Dying - Belwas': {
    name: 'Good Dying - Belwas',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-belwas-ts-t3.png',
    imageUrlBack: '',
  },
  'Count the Cuts - Belwas': {
    name: 'Count the Cuts - Belwas',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-belwas-ts-t4.png',
    imageUrlBack: '',
  },
  'Marshal - Jorah Mormont': {
    name: 'Marshal - Jorah Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-wt-t1.png',
    imageUrlBack: '',
  },
  'Betrayal - Jorah Mormont': {
    name: 'Betrayal - Jorah Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-wt-t2.png',
    imageUrlBack: '',
  },
  'Opportunist - Jorah Mormont': {
    name: 'Opportunist - Jorah Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-wt-t3.png',
    imageUrlBack: '',
  },
  'Feinting Maneuver - Jorah Mormont': {
    name: 'Feinting Maneuver - Jorah Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-jorah-mormont-wt-t4.png',
    imageUrlBack: '',
  },
  'Devotees Of The Dragon - Marselen': {
    name: 'Devotees Of The Dragon - Marselen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-marselen-mmc-t1.jpg',
    imageUrlBack: '',
  },
  'Devastating Impact - Marselen': {
    name: 'Devastating Impact - Marselen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-marselen-mmc-t2.jpg',
    imageUrlBack: '',
  },
  'War Cry - Marselen': {
    name: 'War Cry - Marselen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-marselen-mmc-t3.jpg',
    imageUrlBack: '',
  },
  'Supply Aid - Marselen': {
    name: 'Supply Aid - Marselen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-marselen-mmc-t4.jpg',
    imageUrlBack: '',
  },
  'Keeping The Peace - Skahaz Mo Kandaq': {
    name: 'Keeping The Peace - Skahaz Mo Kandaq',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-skahaz-mo-kandaq-ts-t1.jpg',
    imageUrlBack: '',
  },
  "The Queen's Law - Skahaz Mo Kandaq": {
    name: "The Queen's Law - Skahaz Mo Kandaq",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-skahaz-mo-kandaq-ts-t2.jpg',
    imageUrlBack: '',
  },
  'Eyes Of The Watch - Skahaz Mo Kandaq': {
    name: 'Eyes Of The Watch - Skahaz Mo Kandaq',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-skahaz-mo-kandaq-ts-t3.jpg',
    imageUrlBack: '',
  },
  'Ghiscari Justice - Skahaz Mo Kandaq': {
    name: 'Ghiscari Justice - Skahaz Mo Kandaq',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ht-skahaz-mo-kandaq-ts-t4.jpg',
    imageUrlBack: '',
  },
};

export default cardData;
