import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  Overrun: {
    name: 'Overrun',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-t1.png',
    imageUrlBack: '',
  },
  'Sudden Retreat - Targaryen': {
    name: 'Sudden Retreat - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-t2.png',
    imageUrlBack: '',
  },
  'Swift Reposition - Targaryen': {
    name: 'Swift Reposition - Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-t3.png',
    imageUrlBack: '',
  },
  'Fire and Blood': {
    name: 'Fire and Blood',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-t4.png',
    imageUrlBack: '',
  },
  'Field Control': {
    name: 'Field Control',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-t5.png',
    imageUrlBack: '',
  },
  'Unstoppable Advance': {
    name: 'Unstoppable Advance',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-t6.png',
    imageUrlBack: '',
  },
  'Blood of the Dragon': {
    name: 'Blood of the Dragon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-t7.png',
    imageUrlBack: '',
  },
  'Addrivat!': {
    name: 'Addrivat!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-khal-drogo-tgk-t1.png',
    imageUrlBack: '',
  },
  'Lead by Example': {
    name: 'Lead by Example',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-khal-drogo-tgk-t2.png',
    imageUrlBack: '',
  },
  'Ride-By Attack - Khal Drogo': {
    name: 'Ride-By Attack - Khal Drogo',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-khal-drogo-tgk-t3.png',
    imageUrlBack: '',
  },
  'Assault Orders - Khal Drogo': {
    name: 'Assault Orders - Khal Drogo',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-khal-drogo-tgk-t4.png',
    imageUrlBack: '',
  },
  'Targaryen Supremacy': {
    name: 'Targaryen Supremacy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daenerys-targaryen-qom-t1.png',
    imageUrlBack: '',
  },
  'Subjugation of Power': {
    name: 'Subjugation of Power',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daenerys-targaryen-qom-t2.png',
    imageUrlBack: '',
  },
  'Remorseless Examples - Daenerys Targaryen': {
    name: 'Remorseless Examples - Daenerys Targaryen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daenerys-targaryen-qom-t3.png',
    imageUrlBack: '',
  },
  Counterplot: {
    name: 'Counterplot',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daenerys-targaryen-qom-t4.png',
    imageUrlBack: '',
  },
  'Sustained Assault - Barristan Selmy': {
    name: 'Sustained Assault - Barristan Selmy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-barristan-selmy-tb-t1.png',
    imageUrlBack: '',
  },
  'Combat Prowess': {
    name: 'Combat Prowess',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-barristan-selmy-tb-t2.png',
    imageUrlBack: '',
  },
  'Legendary Boldness': {
    name: 'Legendary Boldness',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-barristan-selmy-tb-t3.png',
    imageUrlBack: '',
  },
  'Victory Comes Hard': {
    name: 'Victory Comes Hard',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-barristan-selmy-tb-t4.png',
    imageUrlBack: '',
  },
  'Dracarys!': {
    name: 'Dracarys!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daenerys-targaryen-mod-t1.png',
    imageUrlBack: '',
  },
  "Dragon's Flight": {
    name: "Dragon's Flight",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daenerys-targaryen-mod-t2.png',
    imageUrlBack: '',
  },
  'Promise of Fire': {
    name: 'Promise of Fire',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daenerys-targaryen-mod-t3.png',
    imageUrlBack: '',
  },
  'Fire Made Flesh': {
    name: 'Fire Made Flesh',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daenerys-targaryen-mod-t4.png',
    imageUrlBack: '',
  },
  'Lash Out - Grey Worm': {
    name: 'Lash Out - Grey Worm',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-grey-worm-uc-t1.png',
    imageUrlBack: '',
  },
  'Battle Endurance': {
    name: 'Battle Endurance',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-grey-worm-uc-t2.png',
    imageUrlBack: '',
  },
  'Retribution of The Dragon': {
    name: 'Retribution of The Dragon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-grey-worm-uc-t3.png',
    imageUrlBack: '',
  },
  'Issue Commands - Grey Worm': {
    name: 'Issue Commands - Grey Worm',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-grey-worm-uc-t4.png',
    imageUrlBack: '',
  },
  'Sellsword Negotiations - Daario Naharis (Targaryen)': {
    name: 'Sellsword Negotiations - Daario Naharis (Targaryen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daario-naharis-sc-t1.png',
    imageUrlBack: '',
  },
  'Sellsword Bravado - Daario Naharis (Targaryen)': {
    name: 'Sellsword Bravado - Daario Naharis (Targaryen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daario-naharis-sc-t2.png',
    imageUrlBack: '',
  },
  'Reckless Strikes - Daario Naharis (Targaryen)': {
    name: 'Reckless Strikes - Daario Naharis (Targaryen)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daario-naharis-sc-t3.png',
    imageUrlBack: '',
  },
  'Hasty Offense': {
    name: 'Hasty Offense',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-daario-naharis-sc-t4.png',
    imageUrlBack: '',
  },
  'Pathetic Attempt - Belwas': {
    name: 'Pathetic Attempt - Belwas',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-belwas-ts-t1.png',
    imageUrlBack: '',
  },
  'Expert Parry': {
    name: 'Expert Parry',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-belwas-ts-t2.png',
    imageUrlBack: '',
  },
  'Good Dying': {
    name: 'Good Dying',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-belwas-ts-t3.png',
    imageUrlBack: '',
  },
  'Count the Cuts': {
    name: 'Count the Cuts',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-belwas-ts-t4.png',
    imageUrlBack: '',
  },
  Marshal: {
    name: 'Marshal',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-jorah-mormont-wt-t1.png',
    imageUrlBack: '',
  },
  Betrayal: {
    name: 'Betrayal',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-jorah-mormont-wt-t2.png',
    imageUrlBack: '',
  },
  'Opportunist - Jorah Mormont': {
    name: 'Opportunist - Jorah Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-jorah-mormont-wt-t3.png',
    imageUrlBack: '',
  },
  'Feinting Manuever': {
    name: 'Feinting Manuever',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/ht-jorah-mormont-wt-t4.png',
    imageUrlBack: '',
  },
};

export default cardData;
