import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Addam Marbrand - Commander Of The City Watch': {
    name: 'Addam Marbrand - Commander Of The City Watch',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-addam-marbrand-cotcw.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-addam-marbrand-cotcw-back.png',
    isCommander: true,
  },
  'Addam Marbrand - Trusted Bannerman': {
    name: 'Addam Marbrand - Trusted Bannerman',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-addam-marbrand-tb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-addam-marbrand-tb-back.png',
  },
  'Arys Oakheart - Kingsguard': {
    name: 'Arys Oakheart - Kingsguard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-arys-oakheart-k.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-arys-oakheart-k-back.png',
  },
  'Assault Veteran': {
    name: 'Assault Veteran',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-assault-veteran.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-assault-veteran-back.png',
  },
  'Barristan Selmy - Lord Commander Of The Kingsguard': {
    name: 'Barristan Selmy - Lord Commander Of The Kingsguard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-barristan-selmy-lcotk.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-barristan-selmy-lcotk-back.png',
  },
  'Boros Blount - Kingsguard': {
    name: 'Boros Blount - Kingsguard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-boros-blount-k.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-boros-blount-k-back.png',
  },
  'Champion Of The Faith': {
    name: 'Champion Of The Faith',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-champion-of-the-faith.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-champion-of-the-faith-back.png',
  },
  'Clegane Butcher': {
    name: 'Clegane Butcher',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-clegane-butcher.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-clegane-butcher-back.png',
  },
  'Gate Warden': {
    name: 'Gate Warden',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-gate-warden.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-gate-warden-back.png',
  },
  "Gregor Clegane - Lord Tywin's Mad Dog": {
    name: "Gregor Clegane - Lord Tywin's Mad Dog",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-gregor-clegane-ltmd.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-gregor-clegane-ltmd-back.png',
  },
  'Gregor Clegane - Mounted Behemoth': {
    name: 'Gregor Clegane - Mounted Behemoth',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-gregor-clegane-mb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-gregor-clegane-mb-back.png',
  },
  'Gregor Clegane - The Mountain': {
    name: 'Gregor Clegane - The Mountain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-gregor-clegane-tm.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-gregor-clegane-tm-back.png',
    isCommander: true,
  },
  'Guard Captain': {
    name: 'Guard Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-guard-captain.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-guard-captain-back.png',
  },
  'The High Sparrow - His High Holiness': {
    name: 'The High Sparrow - His High Holiness',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-high-sparrow-hhh.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-high-sparrow-hhh-back.png',
    isCommander: true,
  },
  'Jaime Lannister - The Kingslayer': {
    name: 'Jaime Lannister - The Kingslayer',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-jaime-lannister-tk.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-jaime-lannister-tk-back.png',
    isCommander: true,
  },
  'Jaime Lannister - Kingsguard': {
    name: 'Jaime Lannister - Kingsguard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-jaime-lannister-k.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-jaime-lannister-k-back.png',
  },
  'Jaime Lannister - The Young Lion': {
    name: 'Jaime Lannister - The Young Lion',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-jaime-lannister-tyl.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-jaime-lannister-tyl-back.png',
  },
  'Joffrey Baratheon - First Of His Name': {
    name: 'Joffrey Baratheon - First Of His Name',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-joffrey-baratheon-fohn.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-joffrey-baratheon-fohn-back.png',
    isCommander: true,
  },
  'Kevan Lannister - Protector Of The Realm': {
    name: 'Kevan Lannister - Protector Of The Realm',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-kevan-lannister-potr.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-kevan-lannister-potr-back.png',
    isCommander: true,
  },
  'Mandon Moore - Kingsguard': {
    name: 'Mandon Moore - Kingsguard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-mandon-moore-k.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-mandon-moore-k-back.png',
  },
  'Meryn Trant - Kingsguard': {
    name: 'Meryn Trant - Kingsguard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-meryn-trant-k.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-meryn-trant-k-back.png',
  },
  'Preston Greenfield - Kingsguard': {
    name: 'Preston Greenfield - Kingsguard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-preston-greenfield-k.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-preston-greenfield-k-back.png',
  },
  'Qyburn - Forbidden Knowledge': {
    name: 'Qyburn - Forbidden Knowledge',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-qyburn-fk.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-qyburn-fk-back.png',
  },
  'Sandor Clegane - The Hound': {
    name: 'Sandor Clegane - The Hound',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-sandor-clegane-th.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-sandor-clegane-th-back.png',
  },
  'Sentinel Enforcer': {
    name: 'Sentinel Enforcer',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-sentinel-enforcer.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-sentinel-enforcer-back.png',
  },
  'Ser Robert Strong - The Silent Giant': {
    name: 'Ser Robert Strong - The Silent Giant',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-ser-robert-strong-tsg.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-ser-robert-strong-tsg-back.png',
  },
  'Tyrion Lannister - Halfman': {
    name: 'Tyrion Lannister - Halfman',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-tyrion-lannister-h.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-tyrion-lannister-h-back.png',
    isCommander: true,
  },
  'Tyrion Lannister - The Giant Of Lannister': {
    name: 'Tyrion Lannister - The Giant Of Lannister',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-tyrion-lannister-tgol.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-tyrion-lannister-tgol-back.png',
  },
  'Tywin Lannister - Lord Of Casterly Rock': {
    name: 'Tywin Lannister - Lord Of Casterly Rock',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-tywin-lannister-locr.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hl-tywin-lannister-locr-back.png',
    isCommander: true,
  },
};

export default cardData;
