import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Intrigue And Subterfuge - Lannister': {
    name: 'Intrigue And Subterfuge - Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-t1.png',
    imageUrlBack: '',
  },
  'A Lannister Pays His Debts - Lannister': {
    name: 'A Lannister Pays His Debts - Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-t2.png',
    imageUrlBack: '',
  },
  'Hear Me Roar! - Lannister': {
    name: 'Hear Me Roar! - Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-t3.png',
    imageUrlBack: '',
  },
  'Bribery - Lannister': {
    name: 'Bribery - Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-t4.png',
    imageUrlBack: '',
  },
  'Counterplot - Lannister': {
    name: 'Counterplot - Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-t5.png',
    imageUrlBack: '',
  },
  'Fealty To The Crown - Lannister': {
    name: 'Fealty To The Crown - Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-t6.png',
    imageUrlBack: '',
  },
  'Subjugation Of Power - Lannister': {
    name: 'Subjugation Of Power - Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-t7.png',
    imageUrlBack: '',
  },
  "Kingslayer's Renown - Jamie Lannister": {
    name: "Kingslayer's Renown - Jamie Lannister",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-jaime-lannister-tk-t1.png',
    imageUrlBack: '',
  },
  "Kingslayer's Prowess - Jamie Lannister": {
    name: "Kingslayer's Prowess - Jamie Lannister",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-jaime-lannister-tk-t2.png',
    imageUrlBack: '',
  },
  "Kingslayer's Infamy - Jamie Lannister": {
    name: "Kingslayer's Infamy - Jamie Lannister",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-jaime-lannister-tk-t3.png',
    imageUrlBack: '',
  },
  'You Will Obey Me! - Joffrey Baratheon': {
    name: 'You Will Obey Me! - Joffrey Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-joffrey-baratheon-fohn-t1.png',
    imageUrlBack: '',
  },
  'Traitors! I Will Have Their Heads! - Joffrey Baratheon': {
    name: 'Traitors! I Will Have Their Heads! - Joffrey Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-joffrey-baratheon-fohn-t2.png',
    imageUrlBack: '',
  },
  'I Am The King! - Joffrey Baratheon': {
    name: 'I Am The King! - Joffrey Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-joffrey-baratheon-fohn-t3.png',
    imageUrlBack: '',
  },
  'False Agenda - Tyrion Lannister': {
    name: 'False Agenda - Tyrion Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-tyrion-lannister-h-t1.png',
    imageUrlBack: '',
  },
  'Cunning Ploy - Tyrion Lannister': {
    name: 'Cunning Ploy - Tyrion Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-tyrion-lannister-h-t2.png',
    imageUrlBack: '',
  },
  'Intercept Orders - Tyrion Lannister': {
    name: 'Intercept Orders - Tyrion Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-tyrion-lannister-h-t3.png',
    imageUrlBack: '',
  },
  'Exploit Weakness - Tywin Lannister': {
    name: 'Exploit Weakness - Tywin Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-tywin-lannister-locr-t1.png',
    imageUrlBack: '',
  },
  'Broken Resolve - Tywin Lannister': {
    name: 'Broken Resolve - Tywin Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-tywin-lannister-locr-t2.png',
    imageUrlBack: '',
  },
  'Issue Commands - Tywin Lannister': {
    name: 'Issue Commands - Tywin Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-tywin-lannister-locr-t3.png',
    imageUrlBack: '',
  },
  'Overrun - Gregor Clegane': {
    name: 'Overrun - Gregor Clegane',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-gregor-clegane-tm-t1.png',
    imageUrlBack: '',
  },
  'Assault Orders - Gregor Clegane': {
    name: 'Assault Orders - Gregor Clegane',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-gregor-clegane-tm-t2.png',
    imageUrlBack: '',
  },
  'Price Of Failure - Gregor Clegane': {
    name: 'Price Of Failure - Gregor Clegane',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-gregor-clegane-tm-t3.png',
    imageUrlBack: '',
  },
  'Mercy Of The Mother - The High Sparrow': {
    name: 'Mercy Of The Mother - The High Sparrow',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-high-sparrow-hhh-t1.png',
    imageUrlBack: '',
  },
  'Protection Of The Father - The High Sparrow': {
    name: 'Protection Of The Father - The High Sparrow',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-high-sparrow-hhh-t2.png',
    imageUrlBack: '',
  },
  'Wrath Of The Warrior - The High Sparrow': {
    name: 'Wrath Of The Warrior - The High Sparrow',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-high-sparrow-hhh-t3.png',
    imageUrlBack: '',
  },
  'Predictable Maneuvers - Kevan Lannister': {
    name: 'Predictable Maneuvers - Kevan Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-kevan-lannister-potr-t1.png',
    imageUrlBack: '',
  },
  'Seeing Their Flaws - Kevan Lannister': {
    name: 'Seeing Their Flaws - Kevan Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-kevan-lannister-potr-t2.png',
    imageUrlBack: '',
  },
  'Wealth Of The Rock - Kevan Lannister': {
    name: 'Wealth Of The Rock - Kevan Lannister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-kevan-lannister-potr-t3.png',
    imageUrlBack: '',
  },
  'Charismatic Leadership - Addam Marbrand': {
    name: 'Charismatic Leadership - Addam Marbrand',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-addam-marbrand-cotcw-t1.png',
    imageUrlBack: '',
  },
  'Lash Out - Addam Marbrand': {
    name: 'Lash Out - Addam Marbrand',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-addam-marbrand-cotcw-t2.png',
    imageUrlBack: '',
  },
  'Valiant Example - Addam Marbrand': {
    name: 'Valiant Example - Addam Marbrand',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hl-addam-marbrand-cotcw-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
