import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Alliser Thorne - Master-at-Arms': {
    name: 'Alliser Thorne - Master-at-Arms',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-alliser-thorne-maa.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-alliser-thorne-maa-back.png',
    isCommander: true,
  },
  'Alliser Thorne - Vindictive Overseer': {
    name: 'Alliser Thorne - Vindictive Overseer',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-alliser-thorne-vo.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-alliser-thorne-vo-back.png',
  },
  'Benjen Stark - Beyond the Wall': {
    name: 'Benjen Stark - Beyond the Wall',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-btw.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-btw-back.png',
    isCommander: true,
  },
  'Benjen Stark - First Ranger': {
    name: 'Benjen Stark - First Ranger',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-fr.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-fr-back.png',
    isCommander: true,
  },
  'Benjen Stark - Wolf Of The Wall': {
    name: 'Benjen Stark - Wolf Of The Wall',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-wotw.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-wotw-back.png',
  },
  'Coldhands - Enigmatic Guide': {
    name: 'Coldhands - Enigmatic Guide',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-coldhands-eg.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-coldhands-eg-back.png',
  },
  'Coldhands - Former Crow': {
    name: 'Coldhands - Former Crow',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-coldhands-fc.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-coldhands-fc-back.png',
  },
  'Cotter Pyke - Eastwatch Commander': {
    name: 'Cotter Pyke - Eastwatch Commander',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-cotter-pyke-ec.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-cotter-pyke-ec-back.png',
    isCommander: true,
  },
  'Cotter Pyke - Ironborn Brother': {
    name: 'Cotter Pyke - Ironborn Brother',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-cotter-pyke-ib.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-cotter-pyke-ib-back.png',
  },
  'Donal Noye - Defender of Castle Black': {
    name: 'Donal Noye - Defender of Castle Black',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-donal-noye-docb.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-donal-noye-docb-back.png',
    isCommander: true,
  },
  'Eddison Tollett - Dolorous Edd': {
    name: 'Eddison Tollett - Dolorous Edd',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-eddison-tollett-de.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-eddison-tollett-de-back.png',
  },
  'Grenn - Aurochs': {
    name: 'Grenn - Aurochs',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-grenn-a.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-grenn-a-back.png',
  },
  'Hardened Ranger': {
    name: 'Hardened Ranger',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-hardened-ranger.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-hardened-ranger-back.png',
  },
  'Jeor Mormont - 997th Lord Commander': {
    name: 'Jeor Mormont - 997th Lord Commander',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jeor-mormont-9lc.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jeor-mormont-9lc-back.png',
    isCommander: true,
  },
  'Jon Snow - 998th Lord Commander': {
    name: 'Jon Snow - 998th Lord Commander',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jon-snow-9lc.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jon-snow-9lc-back.png',
    isCommander: true,
  },
  'Jon Snow - "Lord Snow"': {
    name: 'Jon Snow - "Lord Snow"',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jon-snow-ls.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jon-snow-ls-back.png',
  },
  'Othell Yarwyck - First Builder': {
    name: 'Othell Yarwyck - First Builder',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-othell-yarwyck-fb.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-othell-yarwyck-fb-back.png',
    isCommander: true,
  },
  'Othell Yarwyck - Spotter': {
    name: 'Othell Yarwyck - Spotter',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-othell-yarwyck-s.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-othell-yarwyck-s-back.png',
  },
  'Pypar - Monkey': {
    name: 'Pypar - Monkey',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-pypar-m.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-pypar-m-back.png',
  },
  'Qhorin Halfhand - Grizzled Ranger': {
    name: 'Qhorin Halfhand - Grizzled Ranger',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-qhorin-halfhand-gr.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-qhorin-halfhand-gr-back.png',
  },
  'Samwell Tarley - Sam The Slayer': {
    name: 'Samwell Tarley - Sam The Slayer',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-samwell-tarley-sts.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-samwell-tarley-sts-back.png',
  },
  'Satin - Brave Recruit': {
    name: 'Satin - Brave Recruit',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-satin-br.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-satin-br-back.png',
  },
  "Satin - Commander's Steward": {
    name: "Satin - Commander's Steward",
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-satin-cs.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-satin-cs-back.png',
  },
  'Scorpion Modifications - Builder': {
    name: 'Scorpion Modifications - Builder',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-scorpion-modifications-b.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-scorpion-modifications-b-back.png',
  },
  'Scorpion Modifications - Othell Yarwyck': {
    name: 'Scorpion Modifications - Othell Yarwyck',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-scorpion-modifications-oy.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-scorpion-modifications-oy-back.png',
  },
  'Senior Builder': {
    name: 'Senior Builder',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-senior-builder.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-senior-builder-back.png',
  },
  'Ser Denys Mallister - Shadow Tower Commander': {
    name: 'Ser Denys Mallister - Shadow Tower Commander',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-ser-denys-mallister-stc.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-ser-denys-mallister-stc-back.png',
    isCommander: true,
  },
  'Watch Captain': {
    name: 'Watch Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-watch-captain.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-watch-captain-back.png',
  },
  'Watch Marshal Attachment': {
    name: 'Watch Marshal Attachment',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-watch-marshal-attachment.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-watch-marshal-attachment-back.png',
  },
  'Watch Recruiter': {
    name: 'Watch Recruiter',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-watch-recruiter.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-watch-recruiter-back.png',
  },
  'Yoren - Harsh Recruiter': {
    name: 'Yoren - Harsh Recruiter',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-yoren-hr.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-yoren-hr-back.png',
  },
};

export default cardData;
