import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'The Sword in the Darkness': {
    name: 'The Sword in the Darkness',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-t1.png',
    imageUrlBack: '',
  },
  'the Fire That Burns Against The Cold': {
    name: 'the Fire That Burns Against The Cold',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-t2.png',
    imageUrlBack: '',
  },
  'The Shield of the Realms of Men': {
    name: 'The Shield of the Realms of Men',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-t3.png',
    imageUrlBack: '',
  },
  'The Watcher on the Wall': {
    name: 'The Watcher on the Wall',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-t4.png',
    imageUrlBack: '',
  },
  'The Light That Brings The Dawn': {
    name: 'The Light That Brings The Dawn',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-t5.png',
    imageUrlBack: '',
  },
  'Take The Black': {
    name: 'Take The Black',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-t6.png',
    imageUrlBack: '',
  },
  'And Now His Watch Has Ended': {
    name: 'And Now His Watch Has Ended',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-t7.png',
    imageUrlBack: '',
  },
  'And Now My Watch Begins': {
    name: 'And Now My Watch Begins',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jeor-mormont-9lc-t1.png',
    imageUrlBack: '',
  },
  'Live And Die At My Post': {
    name: 'Live And Die At My Post',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jeor-mormont-9lc-t2.png',
    imageUrlBack: '',
  },
  'Night Gathers': {
    name: 'Night Gathers',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jeor-mormont-9lc-t3.png',
    imageUrlBack: '',
  },
  'Honed Enhancement': {
    name: 'Honed Enhancement',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-othell-yarwyck-fb-t1.png',
    imageUrlBack: '',
  },
  'Rapid Consutrction': {
    name: 'Rapid Consutrction',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-othell-yarwyck-fb-t2.png',
    imageUrlBack: '',
  },
  'Serrated Enhancement': {
    name: 'Serrated Enhancement',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-othell-yarwyck-fb-t3.png',
    imageUrlBack: '',
  },
  'Defensive Formation': {
    name: 'Defensive Formation',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-donal-noye-docb-t1.png',
    imageUrlBack: '',
  },
  'Refuse to Yield': {
    name: 'Refuse to Yield',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-donal-noye-docb-t2.png',
    imageUrlBack: '',
  },
  'Lash Out - Donal Noye': {
    name: 'Lash Out - Donal Noye',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-donal-noye-docb-t3.png',
    imageUrlBack: '',
  },
  'Pathetic Attempt - Alliser Thorne': {
    name: 'Pathetic Attempt - Alliser Thorne',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-alliser-thorne-maa-t1.png',
    imageUrlBack: '',
  },
  'Seeing Their Flaws - Alliser Thorne': {
    name: 'Seeing Their Flaws - Alliser Thorne',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-alliser-thorne-maa-t2.png',
    imageUrlBack: '',
  },
  'Price of Failure - Alliser Thorne': {
    name: 'Price of Failure - Alliser Thorne',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-alliser-thorne-maa-t3.png',
    imageUrlBack: '',
  },
  'It Shall Not End Until My Death!': {
    name: 'It Shall Not End Until My Death!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jon-snow-9lc-t1.png',
    imageUrlBack: '',
  },
  'Stand United, Brothers!': {
    name: 'Stand United, Brothers!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jon-snow-9lc-t2.png',
    imageUrlBack: '',
  },
  'For the Watch!': {
    name: 'For the Watch!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-jon-snow-9lc-t3.png',
    imageUrlBack: '',
  },
  'Hit And Run - Benjen Stark': {
    name: 'Hit And Run - Benjen Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-fr-t1.png',
    imageUrlBack: '',
  },
  'Lying In Wait': {
    name: 'Lying In Wait',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-fr-t2.png',
    imageUrlBack: '',
  },
  "Hunter's Insight - First Ranger": {
    name: "Hunter's Insight - First Ranger",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-fr-t3.png',
    imageUrlBack: '',
  },
  "Hunter's Insight - Beyond The Wall": {
    name: "Hunter's Insight - Beyond The Wall",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-btw-t1.png',
    imageUrlBack: '',
  },
  'Marshal - Benjen Stark': {
    name: 'Marshal - Benjen Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-btw-t2.png',
    imageUrlBack: '',
  },
  'Ride-By-Attack - Benjen Stark': {
    name: 'Ride-By-Attack - Benjen Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-benjen-stark-btw-t3.png',
    imageUrlBack: '',
  },
  'Assault Orders - Cotter Pyke': {
    name: 'Assault Orders - Cotter Pyke',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-cotter-pyke-ec-t1.png',
    imageUrlBack: '',
  },
  'Pyke Aggression': {
    name: 'Pyke Aggression',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-cotter-pyke-ec-t2.png',
    imageUrlBack: '',
  },
  'Reckless Strikes - Cotter Pyke': {
    name: 'Reckless Strikes - Cotter Pyke',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-cotter-pyke-ec-t3.png',
    imageUrlBack: '',
  },
  'Adaptive Methods - Ser Denys Mallister': {
    name: 'Adaptive Methods - Ser Denys Mallister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-ser-denys-mallister-stc-t1.png',
    imageUrlBack: '',
  },
  'Combat Prowess - Ser Denys Mallister': {
    name: 'Combat Prowess - Ser Denys Mallister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-ser-denys-mallister-stc-t2.png',
    imageUrlBack: '',
  },
  'Tempered By Duty': {
    name: 'Tempered By Duty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/nw-ser-denys-mallister-stc-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
