import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  "The Sword In The Darkness - Night's Watch": {
    name: "The Sword In The Darkness - Night's Watch",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-t1.png',
    imageUrlBack: '',
  },
  "The Fire That Burns Against The Cold - Night's Watch": {
    name: "The Fire That Burns Against The Cold - Night's Watch",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-t2.png',
    imageUrlBack: '',
  },
  "The Shield Of The Realms Of Men - Night's Watch": {
    name: "The Shield Of The Realms Of Men - Night's Watch",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-t3.png',
    imageUrlBack: '',
  },
  "The Watcher On The Wall - Night's Watch": {
    name: "The Watcher On The Wall - Night's Watch",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-t4.png',
    imageUrlBack: '',
  },
  "The Light That Brings The Dawn - Night's Watch": {
    name: "The Light That Brings The Dawn - Night's Watch",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-t5.png',
    imageUrlBack: '',
  },
  "Take The Black - Night's Watch": {
    name: "Take The Black - Night's Watch",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-t6.png',
    imageUrlBack: '',
  },
  "And Now His Watch Has Ended - Night's Watch": {
    name: "And Now His Watch Has Ended - Night's Watch",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-t7.png',
    imageUrlBack: '',
  },
  'And Now My Watch Begins - Jeor Mormont': {
    name: 'And Now My Watch Begins - Jeor Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-jeor-mormont-9lc-t1.png',
    imageUrlBack: '',
  },
  'Live And Die At My Post - Jeor Mormont': {
    name: 'Live And Die At My Post - Jeor Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-jeor-mormont-9lc-t2.png',
    imageUrlBack: '',
  },
  'Night Gathers - Jeor Mormont': {
    name: 'Night Gathers - Jeor Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-jeor-mormont-9lc-t3.png',
    imageUrlBack: '',
  },
  'It Shall Not End Until My Death! - Jon Snow': {
    name: 'It Shall Not End Until My Death! - Jon Snow',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-jon-snow-9lc-t1.png',
    imageUrlBack: '',
  },
  'Stand United, Brothers! - Jon Snow': {
    name: 'Stand United, Brothers! - Jon Snow',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-jon-snow-9lc-t2.png',
    imageUrlBack: '',
  },
  'For The Watch! - Jon Snow': {
    name: 'For The Watch! - Jon Snow',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-jon-snow-9lc-t3.png',
    imageUrlBack: '',
  },
  'Honed Enhancement - Othell Yarwyck': {
    name: 'Honed Enhancement - Othell Yarwyck',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-othell-yarwyck-fb-t1.png',
    imageUrlBack: '',
  },
  'Rapid Construction - Othell Yarwyck': {
    name: 'Rapid Construction - Othell Yarwyck',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-othell-yarwyck-fb-t2.png',
    imageUrlBack: '',
  },
  'Serrated Enhancement - Othell Yarwyck': {
    name: 'Serrated Enhancement - Othell Yarwyck',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-othell-yarwyck-fb-t3.png',
    imageUrlBack: '',
  },
  'Defensive Formation - Donal Noye': {
    name: 'Defensive Formation - Donal Noye',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-donal-noye-docb-t1.png',
    imageUrlBack: '',
  },
  'Refuse to Yield - Donal Noye': {
    name: 'Refuse to Yield - Donal Noye',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-donal-noye-docb-t2.png',
    imageUrlBack: '',
  },
  'Lash Out - Donal Noye': {
    name: 'Lash Out - Donal Noye',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-donal-noye-docb-t3.png',
    imageUrlBack: '',
  },
  'Pathetic Attempt - Alliser Thorne': {
    name: 'Pathetic Attempt - Alliser Thorne',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-alliser-thorne-maa-t1.png',
    imageUrlBack: '',
  },
  'Seeing Their Flaws - Alliser Thorne': {
    name: 'Seeing Their Flaws - Alliser Thorne',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-alliser-thorne-maa-t2.png',
    imageUrlBack: '',
  },
  'Price of Failure - Alliser Thorne': {
    name: 'Price of Failure - Alliser Thorne',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-alliser-thorne-maa-t3.png',
    imageUrlBack: '',
  },
  'Hit And Run - Benjen Stark': {
    name: 'Hit And Run - Benjen Stark (First Ranger)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-benjen-stark-fr-t1.png',
    imageUrlBack: '',
  },
  'Lying In Wait - Benjen Stark': {
    name: 'Lying In Wait - Benjen Stark (First Ranger)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-benjen-stark-fr-t2.png',
    imageUrlBack: '',
  },
  "Hunter's Insight - Benjen Stark (First Ranger)": {
    name: "Hunter's Insight - Benjen Stark (First Ranger)",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-benjen-stark-fr-t3.png',
    imageUrlBack: '',
  },
  "Hunter's Insight - Benjen Stark (Beyond The Wall)": {
    name: "Hunter's Insight - Benjen Stark (Beyond The Wall)",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-benjen-stark-btw-t1.png',
    imageUrlBack: '',
  },
  'Marshal - Benjen Stark (Beyond The Wall)': {
    name: 'Marshal - Benjen Stark (Beyond The Wall)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-benjen-stark-btw-t2.png',
    imageUrlBack: '',
  },
  'Ride-By-Attack - Benjen Stark (Beyond The Wall)': {
    name: 'Ride-By-Attack - Benjen Stark (Beyond The Wall)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-benjen-stark-btw-t3.png',
    imageUrlBack: '',
  },
  'Assault Orders - Cotter Pyke': {
    name: 'Assault Orders - Cotter Pyke',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-cotter-pyke-ec-t1.png',
    imageUrlBack: '',
  },
  'Pyke Aggression - Cotter Pyke': {
    name: 'Pyke Aggression - Cotter Pyke',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-cotter-pyke-ec-t2.png',
    imageUrlBack: '',
  },
  'Reckless Strikes - Cotter Pyke': {
    name: 'Reckless Strikes - Cotter Pyke',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-cotter-pyke-ec-t3.png',
    imageUrlBack: '',
  },
  'Adaptive Methods - Ser Denys Mallister': {
    name: 'Adaptive Methods - Ser Denys Mallister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-ser-denys-mallister-stc-t1.png',
    imageUrlBack: '',
  },
  'Combat Prowess - Ser Denys Mallister': {
    name: 'Combat Prowess - Ser Denys Mallister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-ser-denys-mallister-stc-t2.png',
    imageUrlBack: '',
  },
  'Tempered By Duty - Ser Denys Mallister': {
    name: 'Tempered By Duty - Ser Denys Mallister',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-bot.brianchuchua.com/images/nw-ser-denys-mallister-stc-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
