import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'We Do Not Sow - Greyjoy': {
    name: 'We Do Not Sow - Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-t1.png',
    imageUrlBack: '',
  },
  'What Is Dead May Never Die - Greyjoy': {
    name: 'What Is Dead May Never Die - Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-t2.png',
    imageUrlBack: '',
  },
  "The Kraken's Wrath - Greyjoy": {
    name: "The Kraken's Wrath - Greyjoy",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-t3.png',
    imageUrlBack: '',
  },
  'The Iron Price - Greyjoy': {
    name: 'The Iron Price - Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-t4.png',
    imageUrlBack: '',
  },
  'Finger Dance - Greyjoy': {
    name: 'Finger Dance - Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-t5.png',
    imageUrlBack: '',
  },
  'Raiding Call - Greyjoy': {
    name: 'Raiding Call - Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-t6.png',
    imageUrlBack: '',
  },
  'Bless With Stone, Bless With Steel - Greyjoy': {
    name: 'Bless With Stone, Bless With Steel - Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-t7.png',
    imageUrlBack: '',
  },
  'Ironborn Mettle - Asha Greyjoy': {
    name: 'Ironborn Mettle - Asha Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-asha-greyjoy-tkd-t1.png',
    imageUrlBack: '',
  },
  'Raider Bravery - Asha Greyjoy': {
    name: 'Raider Bravery - Asha Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-asha-greyjoy-tkd-t2.png',
    imageUrlBack: '',
  },
  'War Cry - Asha Greyjoy': {
    name: 'War Cry - Asha Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-asha-greyjoy-tkd-t3.png',
    imageUrlBack: '',
  },
  'Rush Of Aggression - Victarion Greyjoy': {
    name: 'Rush Of Aggression - Victarion Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-victarion-greyjoy-tic-t1.png',
    imageUrlBack: '',
  },
  'Assault Orders - Victarion Greyjoy': {
    name: 'Assault Orders - Victarion Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-victarion-greyjoy-tic-t2.png',
    imageUrlBack: '',
  },
  'Sustained Assault - Victarion Greyjoy': {
    name: 'Sustained Assault - Victarion Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-victarion-greyjoy-tic-t3.png',
    imageUrlBack: '',
  },
  'Acceptable Sacrifices - Balon Greyjoy': {
    name: 'Acceptable Sacrifices - Balon Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-balon-greyjoy-tkk-t1.png',
    imageUrlBack: '',
  },
  'Price Of Failure - Balon Greyjoy': {
    name: 'Price Of Failure - Balon Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-balon-greyjoy-tkk-t2.png',
    imageUrlBack: '',
  },
  'The Old Way - Balon Greyjoy': {
    name: 'The Old Way - Balon Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-balon-greyjoy-tkk-t3.png',
    imageUrlBack: '',
  },
  "Iron's Endurance - Erik Ironmaker": {
    name: "Iron's Endurance - Erik Ironmaker",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-erik-ironmaker-ab-t1.png',
    imageUrlBack: '',
  },
  "Steel's Might - Erik Ironmaker": {
    name: "Steel's Might - Erik Ironmaker",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-erik-ironmaker-ab-t2.png',
    imageUrlBack: '',
  },
  "Gold's Allure - Erik Ironmaker": {
    name: "Gold's Allure - Erik Ironmaker",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-erik-ironmaker-ab-t3.png',
    imageUrlBack: '',
  },
  'Devious Methods - Euron Greyjoy': {
    name: 'Devious Methods - Euron Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-euron-greyjoy-lrop-t1.png',
    imageUrlBack: '',
  },
  'Cunning Ploy - Euron Greyjoy': {
    name: 'Cunning Ploy - Euron Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-euron-greyjoy-lrop-t2.png',
    imageUrlBack: '',
  },
  'Mind Games - Euron Greyjoy': {
    name: 'Mind Games - Euron Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-euron-greyjoy-lrop-t3.png',
    imageUrlBack: '',
  },
  'Opportunist - Theon Greyjoy': {
    name: 'Opportunist - Theon Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-theon-greyjoy-pow-t1.png',
    imageUrlBack: '',
  },
  'Diversion Tactics - Theon Greyjoy': {
    name: 'Diversion Tactics - Theon Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-theon-greyjoy-pow-t2.png',
    imageUrlBack: '',
  },
  'Stark Exposure - Theon Greyjoy': {
    name: 'Stark Exposure - Theon Greyjoy',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-theon-greyjoy-pow-t3.png',
    imageUrlBack: '',
  },
  'Lust For Glory - Dagmer Cleftjaw': {
    name: 'Lust For Glory - Dagmer Cleftjaw',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-dagmer-cleftjaw-maa-t1.png',
    imageUrlBack: '',
  },
  'Coordination Tactics - Dagmer Cleftjaw': {
    name: 'Coordination Tactics - Dagmer Cleftjaw',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-dagmer-cleftjaw-maa-t2.png',
    imageUrlBack: '',
  },
  'Knowledge Paid In Iron - Dagmer Cleftjaw': {
    name: 'Knowledge Paid In Iron - Dagmer Cleftjaw',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-dagmer-cleftjaw-maa-t3.png',
    imageUrlBack: '',
  },
  'Lash Out - Baelor Blacktyde': {
    name: 'Lash Out - Baelor Blacktyde',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-baelor-blacktyde-lob-t1.png',
    imageUrlBack: '',
  },
  'Blacktyde Resentment - Baelor Blacktyde': {
    name: 'Blacktyde Resentment - Baelor Blacktyde',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-baelor-blacktyde-lob-t2.png',
    imageUrlBack: '',
  },
  'Blacktyde Conviction - Baelor Blacktyde': {
    name: 'Blacktyde Conviction - Baelor Blacktyde',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hg-baelor-blacktyde-lob-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
