import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Arya Stark - Fugitive Princess': {
    name: 'Arya Stark - Fugitive Princess',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-arya-stark-fp.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-arya-stark-fp-back.png',
  },
  "Biter - Rorge's Mad Dog": {
    name: "Biter - Rorge's Mad Dog",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-biter-rmd.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-biter-rmd-back.png',
  },
  'Bolton Flayer (Neutral)': {
    name: 'Bolton Flayer (Neutral)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-bolton-flayer.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-bolton-flayer-back.png',
  },
  'Brienne - Maid of Tarth': {
    name: 'Brienne - Maid of Tarth',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-brienne-mot.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-brienne-mot-back.png',
  },
  'Bronn - The Sellsword': {
    name: 'Bronn - The Sellsword',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-bronn-ts.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-bronn-ts-back.png',
  },
  'Daario Naharis - Reckless Mercenary (Neutral)': {
    name: 'Daario Naharis - Reckless Mercenary (Neutral)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-daario-naharis-rm.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-daario-naharis-rm-back.png',
  },
  'Daario Naharis - Stormcrow Captain (Neutral)': {
    name: 'Daario Naharis - Stormcrow Captain (Neutral)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-daario-naharis-sc.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-daario-naharis-sc-back.png',
    isCommander: true,
  },
  'Dreadfort Captain (Neutral)': {
    name: 'Dreadfort Captain (Neutral)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-dreadfort-captain.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-dreadfort-captain-back.png',
  },
  'Fortune Seeker': {
    name: 'Fortune Seeker',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-fortune-seeker.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-fortune-seeker-back.png',
  },
  'Glory Seeker': {
    name: 'Glory Seeker',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-glory-seeker.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-glory-seeker-back.png',
  },
  'Golden Company Officer': {
    name: 'Golden Company Officer',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-golden-company-officer.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-golden-company-officer-back.png',
  },
  "Jaqen H'ghar - Unnamed": {
    name: "Jaqen H'ghar - Unnamed",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-jaqen-hghar-u.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-jaqen-hghar-u-back.png',
  },
  'Jokin - Archer Captain': {
    name: 'Jokin - Archer Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-jokin-ac.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-jokin-ac-back.png',
  },
  'Jokin - Stormcrow Captain': {
    name: 'Jokin - Stormcrow Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-jokin-sc.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-jokin-sc-back.png',
    isCommander: true,
  },
  'Lysene Bosun': {
    name: 'Lysene Bosun',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-lysene-bosun.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-lysene-bosun-back.png',
  },
  'Ramsay Snow - Sadist (Neutral)': {
    name: 'Ramsay Snow - Sadist (Neutral)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-ramsay-snow-s.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-ramsay-snow-s-back.png',
  },
  'Ramsay Snow - The Bastard of Bolton': {
    name: 'Ramsay Snow - The Bastard of Bolton',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-ramsay-snow-tbob.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-ramsay-snow-tbob-back.png',
    isCommander: true,
  },
  'Roose Bolton - The Leech Lord': {
    name: 'Roose Bolton - The Leech Lord',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-roose-bolton-tll.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-roose-bolton-tll-back.png',
    isCommander: true,
  },
  'Rorge - The Mad Dog Of Saltpans': {
    name: 'Rorge - The Mad Dog Of Saltpans',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-rorge-tmdos.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-rorge-tmdos-back.png',
  },
  'Sandor Clegane - Fugitive Bodyguard': {
    name: 'Sandor Clegane - Fugitive Bodyguard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-sandor-clegane-fb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-sandor-clegane-fb-back.png',
  },
  'Stormcrow Lieutenant (Neutral)': {
    name: 'Stormcrow Lieutenant (Neutral)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-stormcrow-lieutenant.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-stormcrow-lieutenant-back.png',
  },
  'Theon Greyjoy - Reek (Neutral)': {
    name: 'Theon Greyjoy - Reek (Neutral)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-theon-greyjoy-r.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-theon-greyjoy-r-back.png',
  },
  'The Widower - Stormcrow Captain': {
    name: 'The Widower - Stormcrow Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-the-widower-sc.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-the-widower-sc-back.png',
  },
  'The Widower - Second In Command': {
    name: 'The Widower - Second In Command',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-the-widower-sic.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-the-widower-sic-back.png',
  },
  'Vargo Hoat - The Crippler': {
    name: 'Vargo Hoat - The Crippler',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-vargo-hoat-tc.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-vargo-hoat-tc-back.png',
  },
  'Vargo Hoat - The Goat of Harrenhal': {
    name: 'Vargo Hoat - The Goat of Harrenhal',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-vargo-hoat-tgoh.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/n-vargo-hoat-tgoh-back.png',
    isCommander: true,
  },
};

export default cardData;
