import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Bran and Hodor - Protector and Ward': {
    name: 'Bran and Hodor - Protector and Ward',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-bran-and-hodor-paw.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-bran-and-hodor-paw-back.png',
  },
  'Brynden Tully - Outrider Commander': {
    name: 'Brynden Tully - Outrider Commander',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-oc.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-oc-back.png',
    isCommander: true,
  },
  'Brynden Tully - The Blackfish': {
    name: 'Brynden Tully - The Blackfish',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-tb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-tb-back.png',
    isCommander: true,
  },
  'Brynden Tully - Unyielding Knight': {
    name: 'Brynden Tully - Unyielding Knight',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-uk.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-uk-back.png',
  },
  'Brynden Tully - Vanguard Infiltrator': {
    name: 'Brynden Tully - Vanguard Infiltrator',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-vi.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-vi-back.png',
  },
  'Crannogman Survivalist': {
    name: 'Crannogman Survivalist',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-crannogman-survivalist.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-crannogman-survivalist-back.png',
  },
  'Crannogman Warden': {
    name: 'Crannogman Warden',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-crannogman-warden.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-crannogman-warden-back.png',
  },
  'Eddard Stark - Lord of Winterfell': {
    name: 'Eddard Stark - Lord of Winterfell',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-eddard-stark-low.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-eddard-stark-low-back.png',
    isCommander: true,
  },
  'Greatjon Umber - Fierce Bannerman': {
    name: 'Greatjon Umber - Fierce Bannerman',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-greatjon-umber-fb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-greatjon-umber-fb-back.png',
  },
  'Greatjon Umber - Lord of Last Hearth': {
    name: 'Greatjon Umber - Lord of Last Hearth',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-greatjon-umber-lolh.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-greatjon-umber-lolh-back.png',
    isCommander: true,
  },
  'Howland Reed - Lord of the Crannogs': {
    name: 'Howland Reed - Lord of the Crannogs',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-howland-reed-lotc.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-howland-reed-lotc-back.png',
    isCommander: true,
  },
  'Jojen Reed - Greensight': {
    name: 'Jojen Reed - Greensight',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-jojen-reed-g.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-jojen-reed-g-back.png',
  },
  'Loyalist Captain': {
    name: 'Loyalist Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-loyalist-captain.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-loyalist-captain-back.png',
  },
  'Maege Mormont - Lady of Bear Island': {
    name: 'Maege Mormont - Lady of Bear Island',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-maege-mormont-lobi.png',
    imageUrlBack: '', // TODO: Look into why this image isn't available on ASOIAFBuilder
    isCommander: true,
  },
  'Maege Mormont - The She-Bear': {
    name: 'Maege Mormont - The She-Bear',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-maege-mormont-tsb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-maege-mormont-tsb-back.png',
  },
  'Meera Reed - Cunning Trapper': {
    name: 'Meera Reed - Cunning Trapper',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-meera-reed-ct.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-meera-reed-ct-back.png',
  },
  'Mormont Veteran': {
    name: 'Mormont Veteran',
    type: CardTypes.Attachment,

    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-mormont-veteran.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-mormont-veteran-back.png',
  },
  'Osha - Spearwife Guardian': {
    name: 'Osha - Spearwife Guardian',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-osha-sg.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-osha-sg.png',
    isCommander: true,
  },
  'Rickard Karstark - Lord of Karhold': {
    name: 'Rickard Karstark - Lord of Karhold',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickard-karstark-lok.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickard-karstark-lok-back.png',
    isCommander: true,
  },
  'Rickard Karstark - Vengeful Bannerman': {
    name: 'Rickard Karstark - Vengeful Bannerman',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickard-karstark-vb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickard-karstark-vb-back.png',
  },
  'Rickon Stark - The Prince of Winterfell': {
    name: 'Rickon Stark - The Prince of Winterfell',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickon-stark-pow.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickon-stark-pow-back.png',
  },
  'Robb Stark - The Wolf Lord': {
    name: 'Robb Stark - The Wolf Lord',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-robb-stark-twl.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-robb-stark-twl-back.png',
    isCommander: true,
  },
  'Robb Stark - The Young Wolf': {
    name: 'Robb Stark - The Young Wolf',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-robb-stark-tyw.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-robb-stark-tyw-back.png',
  },
  'Rodrik Cassel - Master-at-Arms': {
    name: 'Rodrik Cassel - Master-at-Arms',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rodrik-cassel-maa.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rodrik-cassel-maa-back.png',
    isCommander: true,
  },
  'Sworn Sword Captain': {
    name: 'Sworn Sword Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-sworn-sword-captain.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-sworn-sword-captain-back.png',
  },
  'Syrio Forel - First Blade of Braavos': {
    name: 'Syrio Forel - First Blade of Braavos',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-syrio-forel-fbob.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-syrio-forel-fbob-back.png',
  },
  'Umber Champion': {
    name: 'Umber Champion',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-umber-champion.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-umber-champion-back.png',
  },
  'Winterfell Champion': {
    name: 'Winterfell Champion',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-winterfell-champion.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-winterfell-champion-back.png',
  },
  'Winterfell Guardian': {
    name: 'Winterfell Guardian',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-winterfell-guardian.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-winterfell-guardian-back.png',
  },
};

export default cardData;
