import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  "Winter's Might - Stark": {
    name: "Winter's Might - Stark",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-t1.png',
    imageUrlBack: '',
  },
  'Northern Ferocity - Stark': {
    name: 'Northern Ferocity - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-t2.png',
    imageUrlBack: '',
  },
  'Devastating Impact - Stark': {
    name: 'Devastating Impact - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-t3.png',
    imageUrlBack: '',
  },
  'The North Remembers - Stark': {
    name: 'The North Remembers - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-t4.png',
    imageUrlBack: '',
  },
  'Swift Reposition - Stark': {
    name: 'Swift Reposition - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-t5.png',
    imageUrlBack: '',
  },
  'Assault Orders - Stark': {
    name: 'Assault Orders - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-t6.png',
    imageUrlBack: '',
  },
  'Winter Is Coming - Stark': {
    name: 'Winter Is Coming - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-t7.png',
    imageUrlBack: '',
  },
  'Sudden Retreat - Robb Stark': {
    name: 'Sudden Retreat - Robb Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-robb-stark-twl-t1.png',
    imageUrlBack: '',
  },
  'Superior Positioning - Robb Stark': {
    name: 'Superior Positioning - Robb Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-robb-stark-twl-t2.png',
    imageUrlBack: '',
  },
  'Hit and Run - Robb Stark': {
    name: 'Hit and Run - Robb Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-robb-stark-twl-t3.png',
    imageUrlBack: '',
  },
  'Berserker Tactics - Greatjon Umber': {
    name: 'Berserker Tactics - Greatjon Umber',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-greatjon-umber-lolh-t1.png',
    imageUrlBack: '',
  },
  'Lash Out - Greatjon Umber': {
    name: 'Lash Out - Greatjon Umber',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-greatjon-umber-lolh-t2.png',
    imageUrlBack: '',
  },
  'Last Stand - Greatjon Umber': {
    name: 'Last Stand - Greatjon Umber',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-greatjon-umber-lolh-t3.png',
    imageUrlBack: '',
  },
  'Ride-By Attack - Brynden Tully (Outrider Commander)': {
    name: 'Ride-By Attack - Brynden Tully (Outrider Commander)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-oc-t1.png',
    imageUrlBack: '',
  },
  'Ride Them Down! - Brynden Tully (Outrider Commander)': {
    name: 'Ride Them Down! - Brynden Tully (Outrider Commander)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-oc-t2.png',
    imageUrlBack: '',
  },
  'Marshal - Brynden Tully (Outrider Commander)': {
    name: 'Marshal - Brynden Tully (Outrider Commander)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-oc-t3.png',
    imageUrlBack: '',
  },
  'Crannog Traps - Howland Reed': {
    name: 'Crannog Traps - Howland Reed',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-howland-reed-lotc-t1.png',
    imageUrlBack: '',
  },
  'Bog Devil Ambush - Howland Reed': {
    name: 'Bog Devil Ambush - Howland Reed',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-howland-reed-lotc-t2.png',
    imageUrlBack: '',
  },
  'The Threat Unseen - Howland Reed': {
    name: 'The Threat Unseen - Howland Reed',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-howland-reed-lotc-t3.png',
    imageUrlBack: '',
  },
  'Combat Prowess - Rodrik Cassel': {
    name: 'Combat Prowess - Rodrik Cassel',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rodrik-cassel-maa-t1.png',
    imageUrlBack: '',
  },
  'Martial Superiority - Rodrik Cassel': {
    name: 'Martial Superiority - Rodrik Cassel',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rodrik-cassel-maa-t2.png',
    imageUrlBack: '',
  },
  'Press The Advantage - Rodrik Cassel': {
    name: 'Press The Advantage - Rodrik Cassel',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rodrik-cassel-maa-t3.png',
    imageUrlBack: '',
  },
  'Northern Defiance - Eddard Stark': {
    name: 'Northern Defiance - Eddard Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-eddard-stark-low-t1.png',
    imageUrlBack: '',
  },
  'Lead By Example - Eddard Stark': {
    name: 'Lead By Example - Eddard Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-eddard-stark-low-t2.png',
    imageUrlBack: '',
  },
  'Fury For The Fallen - Eddard Stark': {
    name: 'Fury For The Fallen - Eddard Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-eddard-stark-low-t3.png',
    imageUrlBack: '',
  },
  'Set For Charge - Brynden Tully (The Blackfish)': {
    name: 'Set For Charge - Brynden Tully (The Blackfish)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-tb-t1.png',
    imageUrlBack: '',
  },
  'Refuse To Yield - Brynden Tully (The Blackfish)': {
    name: 'Refuse To Yield - Brynden Tully (The Blackfish)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-tb-t2.png',
    imageUrlBack: '',
  },
  'War Cry - Brynden Tully (The Blackfish)': {
    name: 'War Cry - Brynden Tully (The Blackfish)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-brynden-tully-tb-t3.png',
    imageUrlBack: '',
  },
  'Taunt - Rickard Karstark': {
    name: 'Taunt - Rickard Karstark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickard-karstark-lok-t1.png',
    imageUrlBack: '',
  },
  'A Need For Vengeance - Rickard Karstark': {
    name: 'A Need For Vengeance - Rickard Karstark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickard-karstark-lok-t2.png',
    imageUrlBack: '',
  },
  'Karstark Retribution - Rickard Karstark': {
    name: 'Karstark Retribution - Rickard Karstark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-rickard-karstark-lok-t3.png',
    imageUrlBack: '',
  },
  'Here We Stand! - Maege Mormont': {
    name: 'Here We Stand! - Maege Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-maege-mormont-lobi-t1.png',
    imageUrlBack: '',
  },
  'Support Of Bear Island - Maege Mormont': {
    name: 'Support Of Bear Island - Maege Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-maege-mormont-lobi-t2.png',
    imageUrlBack: '',
  },
  'Sustained Assault - Maege Mormont': {
    name: 'Sustained Assault - Maege Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hs-maege-mormont-lobi-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
