import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  "Winter's Might": {
    name: "Winter's Might",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-t1.png',
    imageUrlBack: '',
  },
  'Northern Ferocity': {
    name: 'Northern Ferocity',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-t2.png',
    imageUrlBack: '',
  },
  'Devastating Impact - Stark': {
    name: 'Devastating Impact - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-t3.png',
    imageUrlBack: '',
  },
  'The North Remembers': {
    name: 'The North Remembers',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-t4.png',
    imageUrlBack: '',
  },
  'Swift Reposition - Stark': {
    name: 'Swift Reposition - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-t5.png',
    imageUrlBack: '',
  },
  'Assault Orders - Stark': {
    name: 'Assault Orders - Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-t6.png',
    imageUrlBack: '',
  },
  'Winter Is Coming': {
    name: 'Winter Is Coming',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-t7.png',
    imageUrlBack: '',
  },
  'Sudden Retreat - Robb Stark': {
    name: 'Sudden Retreat - Robb Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-robb-stark-twl-t1.png',
    imageUrlBack: '',
  },
  'Superior Positioning - Robb Stark': {
    name: 'Superior Positioning - Robb Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-robb-stark-twl-t2.png',
    imageUrlBack: '',
  },
  'Hit and Run - Robb Stark': {
    name: 'Hit and Run - Robb Stark',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-robb-stark-twl-t3.png',
    imageUrlBack: '',
  },
  'Berserker Tactics': {
    name: 'Berserker Tactics',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-greatjon-umber-lolh-t1.png',
    imageUrlBack: '',
  },
  'Lash Out - Greatjon Umber': {
    name: 'Lash Out - Greatjon Umber',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-greatjon-umber-lolh-t2.png',
    imageUrlBack: '',
  },
  'Last Stand': {
    name: 'Last Stand',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-greatjon-umber-lolh-t3.png',
    imageUrlBack: '',
  },
  'Ride-By Attack - Brynden Tully': {
    name: 'Ride-By Attack - Brynden Tully',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-brynden-tully-oc-t1.png',
    imageUrlBack: '',
  },
  'Ride Them Down!': {
    name: 'Ride Them Down!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-brynden-tully-oc-t2.png',
    imageUrlBack: '',
  },
  'Marshal - Brynden Tully': {
    name: 'Marshal - Brynden Tully',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-brynden-tully-oc-t3.png',
    imageUrlBack: '',
  },
  'Crannog Traps': {
    name: 'Crannog Traps',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-howland-reed-lotc-t1.png',
    imageUrlBack: '',
  },
  'Bog Devil Ambush': {
    name: 'Bog Devil Ambush',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-howland-reed-lotc-t2.png',
    imageUrlBack: '',
  },
  'The Threat Unseen': {
    name: 'The Threat Unseen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-howland-reed-lotc-t3.png',
    imageUrlBack: '',
  },
  'Combat Prowess - Rodrik Cassel': {
    name: 'Combat Prowess - Rodrik Cassel',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-rodrik-cassel-maa-t1.png',
    imageUrlBack: '',
  },
  'Martial Superiority - Rodrik Cassel': {
    name: 'Martial Superiority - Rodrik Cassel',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-rodrik-cassel-maa-t2.png',
    imageUrlBack: '',
  },
  'Press The Advantage': {
    name: 'Press The Advantage',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-rodrik-cassel-maa-t3.png',
    imageUrlBack: '',
  },
  'Northern Defiance': {
    name: 'Northern Defiance',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-eddard-stark-low-t1.png',
    imageUrlBack: '',
  },
  'Lead By Example': {
    name: 'Lead By Example',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-eddard-stark-low-t2.png',
    imageUrlBack: '',
  },
  'Fury For The Fallen': {
    name: 'Fury For The Fallen',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-eddard-stark-low-t3.png',
    imageUrlBack: '',
  },
  'Set For Charge': {
    name: 'Set For Charge',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-brynden-tully-tb-t1.png',
    imageUrlBack: '',
  },
  'Refuse To Yield': {
    name: 'Refuse To Yield',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-brynden-tully-tb-t2.png',
    imageUrlBack: '',
  },
  'War Cry - Brynden Tully': {
    name: 'War Cry - Brynden Tully',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-brynden-tully-tb-t3.png',
    imageUrlBack: '',
  },
  Taunt: {
    name: 'Taunt',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-rickard-karstark-lok-t1.png',
    imageUrlBack: '',
  },
  'A Need For Vengeance': {
    name: 'A Need For Vengeance',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-rickard-karstark-lok-t2.png',
    imageUrlBack: '',
  },
  'Karstark Retribution': {
    name: 'Karstark Retribution',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-rickard-karstark-lok-t3.png',
    imageUrlBack: '',
  },
  'Here We Stand!': {
    name: 'Here We Stand!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-maege-mormont-lobi-t1.png',
    imageUrlBack: '',
  },
  'Support Of Bear Island': {
    name: 'Support Of Bear Island',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-maege-mormont-lobi-t2.png',
    imageUrlBack: '',
  },
  'Sustained Assault - Maege Mormont': {
    name: 'Sustained Assault - Maege Mormont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hs-maege-mormont-lobi-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
