import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  "Andrew Estermont - First Of The King's Men": {
    name: "Andrew Estermont - First Of The King's Men",
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-andrew-estermont-fotkm.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-andrew-estermont-fotkm-back.png',
    isCommander: true,
  },
  'Andrew Estermont - True Loyalist': {
    name: 'Andrew Estermont - True Loyalist',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-andrew-estermont-tl.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-andrew-estermont-tl-back.png',
  },
  'Axell Florent - Fanatical Devotee': {
    name: 'Axell Florent - Fanatical Devotee',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-axell-florent-fd.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-axell-florent-fd-back.png',
  },
  "Axell Florent - First Of The Queen's Men": {
    name: "Axell Florent - First Of The Queen's Men",
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-axell-florent-fotqm.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-axell-florent-fotqm-back.png',
    isCommander: true,
  },
  'Brienne - The Blue': {
    name: 'Brienne - The Blue',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-brienne-tb.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-brienne-tb-back.png',
  },
  "Cortnay Penrose - Castellan Of Storm's End": {
    name: "Cortnay Penrose - Castellan Of Storm's End",
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-cortnay-penrose-cose.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-cortnay-penrose-cose-back.png',
    isCommander: true,
  },
  'Davos Seaworth - Hero Of Blackwater': {
    name: 'Davos Seaworth - Hero Of Blackwater',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-davos-seaworth-hob.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-davos-seaworth-hob-back.png',
    isCommander: true,
  },
  'Davos Seaworth - Onion Knight': {
    name: 'Davos Seaworth - Onion Knight',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-davos-seaworth-ok.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-davos-seaworth-ok-back.png',
  },
  "Devan Seaworth - King's Squire": {
    name: "Devan Seaworth - King's Squire",
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-devan-seaworth-ks.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-devan-seaworth-ks-back.png',
  },
  'Dragonstone Noble': {
    name: 'Dragonstone Noble',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-dragonstone-noble.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-dragonstone-noble-back.png',
  },
  'Eldon Estermont - Lord Of Greenstone': {
    name: 'Eldon Estermont - Lord Of Greenstone',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-eldon-estermont-log.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-eldon-estermont-log-back.png',
    isCommander: true,
  },
  "Loras Tyrell - King's Squire": {
    name: "Loras Tyrell - King's Squire",
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-loras-tyrell-ks.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-loras-tyrell-ks-back.png',
  },
  'Loras Tyrell - The Knight Of Flowers': {
    name: 'Loras Tyrell - The Knight Of Flowers',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-loras-tyrell-tkof.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-loras-tyrell-tkof-back.png',
    isCommander: true,
  },
  'Master Warden': {
    name: 'Master Warden',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-master-warden.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-master-warden-back.png',
  },
  'Pikemen Captain': {
    name: 'Pikemen Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-pikeman-captain.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-pikeman-captain-back.png',
  },
  'Red Priestess': {
    name: 'Red Priestess',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-red-priestess.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-red-priestess-back.png',
  },
  'Renly Baratheon - Lord Paramount Of The Stormlands': {
    name: 'Renly Baratheon - Lord Paramount Of The Stormlands',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-lpots.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-lpots-back.png',
    isCommander: true,
  },
  'Renly Baratheon - The Charismatic Heir': {
    name: 'Renly Baratheon - The Charismatic Heir',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-tch.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-tch-back.png',
    isCommander: true,
  },
  'Stag Knight Noble': {
    name: 'Stag Knight Noble',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stag-knight-noble.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stag-knight-noble-back.png',
  },
  'Stannis Baratheon - The One True King': {
    name: 'Stannis Baratheon - The One True King',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-totk.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-totk-back.png',
    isCommander: true,
  },
  'Stannis Baratheon - The Rightful Heir': {
    name: 'Stannis Baratheon - The Rightful Heir',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-trh.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-trh-back.png',
    isCommander: true,
  },
  'Thorn Watch Sentinel': {
    name: 'Thorn Watch Sentinel',
    type: CardTypes.Attachment,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-thorn-watch-sentinel.png',
    imageUrlBack: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-thorn-watch-sentinel-back.png',
  },
};

export default cardData;
