import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  "Andrew Estermont - First Of The King's Men": {
    name: "Andrew Estermont - First Of The King's Men",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-andrew-estermont-fotkm.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-andrew-estermont-fotkm-back.png',
    isCommander: true,
  },
  'Andrew Estermont - True Loyalist': {
    name: 'Andrew Estermont - True Loyalist',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-andrew-estermont-tl.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-andrew-estermont-tl-back.png',
  },
  'Axell Florent - Fanatical Devotee': {
    name: 'Axell Florent - Fanatical Devotee',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-axell-florent-fd.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-axell-florent-fd-back.png',
  },
  "Axell Florent - First Of The Queen's Men": {
    name: "Axell Florent - First Of The Queen's Men",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-axell-florent-fotqm.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-axell-florent-fotqm-back.png',
    isCommander: true,
  },
  'Brienne - The Blue': {
    name: 'Brienne - The Blue',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-brienne-tb.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-brienne-tb-back.png',
  },
  "Cortnay Penrose - Castellan Of Storm's End": {
    name: "Cortnay Penrose - Castellan Of Storm's End",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-cortnay-penrose-cose.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-cortnay-penrose-cose-back.png',
    isCommander: true,
  },
  'Davos Seaworth - Hero Of Blackwater': {
    name: 'Davos Seaworth - Hero Of Blackwater',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-davos-seaworth-hob.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-davos-seaworth-hob-back.png',
    isCommander: true,
  },
  'Davos Seaworth - Onion Knight': {
    name: 'Davos Seaworth - Onion Knight',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-davos-seaworth-ok.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-davos-seaworth-ok-back.png',
  },
  "Devan Seaworth - King's Squire": {
    name: "Devan Seaworth - King's Squire",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-devan-seaworth-ks.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-devan-seaworth-ks-back.png',
  },
  'Dragonstone Noble (Attachment)': {
    name: 'Dragonstone Noble (Attachment)',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-dragonstone-noble.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-dragonstone-noble-back.png',
  },
  'Eldon Estermont - Lord Of Greenstone': {
    name: 'Eldon Estermont - Lord Of Greenstone',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-eldon-estermont-log.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-eldon-estermont-log-back.png',
    isCommander: true,
  },
  "Loras Tyrell - King's Squire": {
    name: "Loras Tyrell - King's Squire",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-ks.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-ks-back.png',
  },
  'Loras Tyrell - The Knight Of Flowers': {
    name: 'Loras Tyrell - The Knight Of Flowers',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-tkof.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-tkof-back.png',
    isCommander: true,
  },
  'Master Warden': {
    name: 'Master Warden',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-master-warden.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-master-warden-back.png',
  },
  'Pikemen Captain': {
    name: 'Pikemen Captain',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-pikeman-captain.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-pikeman-captain-back.png',
  },
  'Red Priestess': {
    name: 'Red Priestess',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-red-priestess.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-red-priestess-back.png',
  },
  'Renly Baratheon - Lord Paramount Of The Stormlands': {
    name: 'Renly Baratheon - Lord Paramount Of The Stormlands',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-lpots.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-lpots-back.png',
    isCommander: true,
  },
  'Renly Baratheon - The Charismatic Heir': {
    name: 'Renly Baratheon - The Charismatic Heir',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-tch.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-tch-back.png',
    isCommander: true,
  },
  'Stag Knight Noble': {
    name: 'Stag Knight Noble',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stag-knight-noble.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stag-knight-noble-back.png',
  },
  'Stannis Baratheon - The One True King': {
    name: 'Stannis Baratheon - The One True King',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-totk.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-totk-back.png',
    isCommander: true,
  },
  'Stannis Baratheon - The Rightful Heir': {
    name: 'Stannis Baratheon - The Rightful Heir',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-trh.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-trh-back.png',
    isCommander: true,
  },
  'Thorn Watch Sentinel': {
    name: 'Thorn Watch Sentinel',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-thorn-watch-sentinel.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-thorn-watch-sentinel-back.png',
  },
  'Stannis Baratheon - King at the Wall': {
    name: 'Stannis Baratheon - King at the Wall',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-katw.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-katw-back.png',
    isCommander: true,
  },
  "Bryen Farring - King's Squire": {
    name: "Bryen Farring - King's Squire",
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-bryen-farring-ks.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-bryen-farring-ks-back.png',
  },
  'Justin Massey - Cunning Follower': {
    name: 'Justin Massey - Cunning Follower',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-justin-massey-cf.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-justin-massey-cf-back.png',
  },
  'Justin Massey - The Smiler': {
    name: 'Justin Massey - The Smiler',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-justin-massey-ts.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-justin-massey-ts-back.png',
    isCommander: true,
  },
  'Dale Seaworth - Captain of the Wraith': {
    name: 'Dale Seaworth - Captain of the Wraith',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-dale-seaworth-cotw.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-dale-seaworth-cotw-back.png',
  },
  'Renly Baratheon - King in the South': {
    name: 'Renly Baratheon - King in the South',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-kits.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-kits-back.png',
    isCommander: true,
  },
  'Loras Tyrell - Lord Commander of the Rainbow Guard': {
    name: 'Loras Tyrell - Lord Commander of the Rainbow Guard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-lcotrg.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-lcotrg-back.png',
  },
  'Bryce Caron - Bryce the Orange': {
    name: 'Bryce Caron - Bryce the Orange',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-bryce-caron-bto.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-bryce-caron-bto-back.png',
  },
  'Brienne - Rainbow Guard': {
    name: 'Brienne - Rainbow Guard',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-brienne-rg.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-brienne-rg-back.png',
  },
  'Parmen Crane - Parmen the Purple': {
    name: 'Parmen Crane - Parmen the Purple',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-parmen-crane-ptp.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-parmen-crane-ptp-back.png',
  },
  'Emmon Cuy - Emmon the Yellow': {
    name: 'Emmon Cuy - Emmon the Yellow',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-emmon-cuy-ety.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-emmon-cuy-ety-back.png',
  },
  'Robar Royce - Robar the Red': {
    name: 'Robar Royce - Robar the Red',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-robar-royce-rtr.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-robar-royce-rtr-back.png',
  },
  'Guyard Morrigen - Guyard the Green': {
    name: 'Guyard Morrigen - Guyard the Green',
    type: CardTypes.Attachment,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-guyard-morrigen-gtg.png',
    imageUrlBack: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-guyard-morrigen-gtg-back.png',
  },
};

export default cardData;
