import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Baratheon Justice - Baratheon': {
    name: 'Baratheon Justice - Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-t1.png',
    imageUrlBack: '',
  },
  "Stag's Wit - Baratheon": {
    name: "Stag's Wit - Baratheon",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-t2.png',
    imageUrlBack: '',
  },
  'Ours is the Fury! - Baratheon': {
    name: 'Ours is the Fury! - Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-t3.png',
    imageUrlBack: '',
  },
  'Sustained Assault - Baratheon': {
    name: 'Sustained Assault - Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-t4.png',
    imageUrlBack: '',
  },
  'Baratheon Conviction - Baratheon': {
    name: 'Baratheon Conviction - Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-t5.png',
    imageUrlBack: '',
  },
  'Final Strike - Baratheon': {
    name: 'Final Strike - Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-t6.png',
    imageUrlBack: '',
  },
  'Oath of Duty - Baratheon': {
    name: 'Oath of Duty - Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-t7.png',
    imageUrlBack: '',
  },
  'Wealth and Charisma - Renly Baratheon (The Charismatic Heir)': {
    name: 'Wealth and Charisma - Renly Baratheon (The Charismatic Heir)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-tch-t1.png',
    imageUrlBack: '',
  },
  'Younger, Bolder, and Far More Comely - Renly Baratheon (The Charismatic Heir)': {
    name: 'Younger, Bolder, and Far More Comely - Renly Baratheon (The Charismatic Heir)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-tch-t2.png',
    imageUrlBack: '',
  },
  'They Will Make Me King! - Renly Baratheon (The Charismatic Heir)': {
    name: 'They Will Make Me King! - Renly Baratheon (The Charismatic Heir)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-tch-t3.png',
    imageUrlBack: '',
  },
  'Will of the One True King - Stannis Baratheon (The Rightful Heir)': {
    name: 'Will of the One True King - Stannis Baratheon (The Rightful Heir)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-trh-t1.png',
    imageUrlBack: '',
  },
  'Harsh Conditions - Stannis Baratheon (The Rightful Heir)': {
    name: 'Harsh Conditions - Stannis Baratheon (The Rightful Heir)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-trh-t2.png',
    imageUrlBack: '',
  },
  'Tactical Approach - Stannis Baratheon (The Rightful Heir)': {
    name: 'Tactical Approach - Stannis Baratheon (The Rightful Heir)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-trh-t3.png',
    imageUrlBack: '',
  },
  'Inexplicable Return - Renly Baratheon (Lord Paramount)': {
    name: 'Inexplicable Return - Renly Baratheon (Lord Paramount)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-lpots-t1.png',
    imageUrlBack: '',
  },
  'Hidden Affairs - Renly Baratheon (Lord Paramount)': {
    name: 'Hidden Affairs - Renly Baratheon (Lord Paramount)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-lpots-t2.png',
    imageUrlBack: '',
  },
  "In His Brothers' Shadows - Renly Baratheon (Lord Paramount)": {
    name: "In His Brothers' Shadows - Renly Baratheon (Lord Paramount)",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-lpots-t3.png',
    imageUrlBack: '',
  },
  'Loved by the Smallfolk - Loras Tyrell': {
    name: 'Loved by the Smallfolk - Loras Tyrell',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-tkof-t1.png',
    imageUrlBack: '',
  },
  'Overgrowth - Loras Tyrell': {
    name: 'Overgrowth - Loras Tyrell',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-tkof-t2.png',
    imageUrlBack: '',
  },
  'Growing Strong - Loras Tyrell': {
    name: 'Growing Strong - Loras Tyrell',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-loras-tyrell-tkof-t3.png',
    imageUrlBack: '',
  },
  'Flea Bottom Tricks - Davos Seaworth': {
    name: 'Flea Bottom Tricks - Davos Seaworth',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-davos-seaworth-hob-t1.png',
    imageUrlBack: '',
  },
  '"Everything" - Davos Seaworth': {
    name: '"Everything" - Davos Seaworth',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-davos-seaworth-hob-t2.png',
    imageUrlBack: '',
  },
  'Fealty to The Crown - Davos Seaworth': {
    name: 'Fealty to The Crown - Davos Seaworth',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-davos-seaworth-hob-t3.png',
    imageUrlBack: '',
  },
  'Parlay - Davos Seaworth': {
    name: 'Parlay - Davos Seaworth',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-davos-seaworth-hob-t4.png',
    imageUrlBack: '',
  },
  'Hefty Ransom - Eldon Estermont': {
    name: 'Hefty Ransom - Eldon Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-eldon-estermont-log-t1.png',
    imageUrlBack: '',
  },
  'Martial Superiority - Eldon Estermont': {
    name: 'Martial Superiority - Eldon Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-eldon-estermont-log-t2.png',
    imageUrlBack: '',
  },
  'Battle Endurance - Eldon Estermont': {
    name: 'Battle Endurance - Eldon Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-eldon-estermont-log-t3.png',
    imageUrlBack: '',
  },
  'Issue Commands - Cortnay Penrose': {
    name: 'Issue Commands - Cortnay Penrose',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-cortnay-penrose-cose-t1.png',
    imageUrlBack: '',
  },
  'Surprise Strategy - Cortnay Penrose': {
    name: 'Surprise Strategy - Cortnay Penrose',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-cortnay-penrose-cose-t2.png',
    imageUrlBack: '',
  },
  'Counterplot - Courtnay Penrose': {
    name: 'Counterplot - Courtnay Penrose',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-cortnay-penrose-cose-t3.png',
    imageUrlBack: '',
  },
  "In R'hllor's Name - Stannis Baratheon (The One True King)": {
    name: "In R'hllor's Name - Stannis Baratheon (The One True King)",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-totk-t1.png',
    imageUrlBack: '',
  },
  'Test of Faith - Stannis Baratheon (The One True King)': {
    name: 'Test of Faith - Stannis Baratheon (The One True King)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-totk-t2.png',
    imageUrlBack: '',
  },
  'Azor Ahai! - Stannis Baratheon (The One True King)': {
    name: 'Azor Ahai! - Stannis Baratheon (The One True King)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-totk-t3.png',
    imageUrlBack: '',
  },
  'Fiery Charge - Axell Florent': {
    name: 'Fiery Charge - Axell Florent',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-axell-florent-fotqm-t1.png',
    imageUrlBack: '',
  },
  "R'hllor's Wrath - Axell Florent": {
    name: "R'hllor's Wrath - Axell Florent",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-axell-florent-fotqm-t2.png',
    imageUrlBack: '',
  },
  'Fiery Resolve - Axell Florent': {
    name: 'Fiery Resolve - Axell Florent',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-axell-florent-fotqm-t3.png',
    imageUrlBack: '',
  },
  'Assault Orders - Andrew Estermont': {
    name: 'Assault Orders - Andrew Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-andrew-estermont-fotkm-t1.png',
    imageUrlBack: '',
  },
  'Reckless Fury - Andrew Estermont': {
    name: 'Reckless Fury - Andrew Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-andrew-estermont-fotkm-t2.png',
    imageUrlBack: '',
  },
  'Rush of Aggression - Andrew Estermont': {
    name: 'Rush of Aggression - Andrew Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-andrew-estermont-fotkm-t3.png',
    imageUrlBack: '',
  },
  'Muster - Stannis Baratheon (King at the Wall)': {
    name: 'Muster - Stannis Baratheon (King at the Wall)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-katw-t1.png',
    imageUrlBack: '',
  },
  'On the Double! - Stannis Baratheon (King at the Wall)': {
    name: 'On the Double! - Stannis Baratheon (King at the Wall)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-katw-t2.png',
    imageUrlBack: '',
  },
  'Ride Them Down! - Stannis Baratheon (King at the Wall)': {
    name: 'Ride Them Down! - Stannis Baratheon (King at the Wall)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-stannis-baratheon-katw-t3.png',
    imageUrlBack: '',
  },
  'Regroup and Reform - Justin Massey (The Smiler)': {
    name: 'Regroup and Reform - Justin Massey (The Smiler)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-justin-massey-ts-t1.png',
    imageUrlBack: '',
  },
  'Sudden Retreat - Justin Massey (The Smiler)': {
    name: 'Sudden Retreat - Justin Massey (The Smiler)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-justin-massey-ts-t2.png',
    imageUrlBack: '',
  },
  'Precious Supplies - Justin Massey (The Smiler)': {
    name: 'Precious Supplies - Justin Massey (The Smiler)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-justin-massey-ts-t3.png',
    imageUrlBack: '',
  },
  'Overconfidence - Renly Baratheon (King in the South)': {
    name: 'Overconfidence - Renly Baratheon (King in the South)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-kits-t1.png',
    imageUrlBack: '',
  },
  'Knights of Summer - Renly Baratheon (King in the South)': {
    name: 'Knights of Summer - Renly Baratheon (King in the South)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-kits-t2.png',
    imageUrlBack: '',
  },
  'Lavish Encampment - Renly Baratheon (King in the South)': {
    name: 'Lavish Encampment - Renly Baratheon (King in the South)',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/hb-renly-baratheon-kits-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
