import { CardData, CardTypes } from '../types';

const cardData: CardData = {
  'Ours is the Fury!': {
    name: 'Ours is the Fury!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-t1.png',
    imageUrlBack: '',
  },
  'Oath of Duty': {
    name: 'Oath of Duty',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-t2.png',
    imageUrlBack: '',
  },
  "Stag's Wit": {
    name: "Stag's Wit",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-t3.png',
    imageUrlBack: '',
  },
  'Sustained Assault - Baratheon': {
    name: 'Sustained Assault - Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-t4.png',
    imageUrlBack: '',
  },
  'Final Strike - Baratheon': {
    name: 'Final Strike - Baratheon',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-t5.png',
    imageUrlBack: '',
  },
  'Baratheon Conviction': {
    name: 'Baratheon Conviction',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-t6.png',
    imageUrlBack: '',
  },
  'Baratheon Justice': {
    name: 'Baratheon Justice',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-t7.png',
    imageUrlBack: '',
  },
  'Wealth and Charisma': {
    name: 'Wealth and Charisma',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-tch-t1.png',
    imageUrlBack: '',
  },
  'Younger, Bolder, and Far More Comely': {
    name: 'Younger, Bolder, and Far More Comely',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-tch-t2.png',
    imageUrlBack: '',
  },
  'They Will Make Me King!': {
    name: 'They Will Make Me King!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-tch-t3.png',
    imageUrlBack: '',
  },
  'Will of the One True King': {
    name: 'Will of the One True King',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-trh-t1.png',
    imageUrlBack: '',
  },
  'Harsh Conditions': {
    name: 'Harsh Conditions',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-trh-t2.png',
    imageUrlBack: '',
  },
  'Tactical Approach - Stannis': {
    name: 'Tactical Approach - Stannis',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-trh-t3.png',
    imageUrlBack: '',
  },
  'Inexplicable Return': {
    name: 'Inexplicable Return',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-lpots-t1.png',
    imageUrlBack: '',
  },
  'Hidden Affairs': {
    name: 'Hidden Affairs',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-lpots-t2.png',
    imageUrlBack: '',
  },
  "In His Brothers' Shadows": {
    name: "In His Brothers' Shadows",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-renly-baratheon-lpots-t3.png',
    imageUrlBack: '',
  },
  'Loved by the Smallfolk': {
    name: 'Loved by the Smallfolk',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-loras-tyrell-tkof-t1.png',
    imageUrlBack: '',
  },
  Overgrowth: {
    name: 'Overgrowth',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-loras-tyrell-tkof-t2.png',
    imageUrlBack: '',
  },
  'Growing Strong': {
    name: 'Growing Strong',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-loras-tyrell-tkof-t3.png',
    imageUrlBack: '',
  },
  '"Everything"': {
    name: '"Everything"',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-davos-seaworth-hob-t1.png',
    imageUrlBack: '',
  },
  'Fealty to The Crown': {
    name: 'Fealty to The Crown',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-davos-seaworth-hob-t2.png',
    imageUrlBack: '',
  },
  'Parlay - Davos Seaworth': {
    name: 'Parlay - Davos Seaworth',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-davos-seaworth-hob-t3.png',
    imageUrlBack: '',
  },
  'Flea Bottom Tricks': {
    name: 'Flea Bottom Tricks',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-davos-seaworth-hob-t4.png',
    imageUrlBack: '',
  },
  'Hefty Random': {
    name: 'Hefty Random',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-eldon-estermont-log-t1.png',
    imageUrlBack: '',
  },
  'Martial Superiority - Eldon Estermont': {
    name: 'Martial Superiority - Eldon Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-eldon-estermont-log-t2.png',
    imageUrlBack: '',
  },
  'Battle Endurance - Eldon Estermont': {
    name: 'Battle Endurance - Eldon Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-eldon-estermont-log-t3.png',
    imageUrlBack: '',
  },
  'Issue Commands - Cortnay Penrose': {
    name: 'Issue Commands - Cortnay Penrose',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-cortnay-penrose-cose-t1.png',
    imageUrlBack: '',
  },
  'Surprise Strategy - Cortnay Penrose': {
    name: 'Surprise Strategy - Cortnay Penrose',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-cortnay-penrose-cose-t2.png',
    imageUrlBack: '',
  },
  'Counterplot - Courtnay Penrose': {
    name: 'Counterplot - Courtnay Penrose',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-cortnay-penrose-cose-t3.png',
    imageUrlBack: '',
  },
  "In R'hllor's Name": {
    name: "In R'hllor's Name",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-totk-t1.png',
    imageUrlBack: '',
  },
  'Test of Faith': {
    name: 'Test of Faith',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-totk-t2.png',
    imageUrlBack: '',
  },
  'Azor Ahai!': {
    name: 'Azor Ahai!',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-stannis-baratheon-totk-t3.png',
    imageUrlBack: '',
  },
  'Fiery Charge': {
    name: 'Fiery Charge',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-axell-florent-fotqm-t1.png',
    imageUrlBack: '',
  },
  "R'hllor's Wrath": {
    name: "R'hllor's Wrath",
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-axell-florent-fotqm-t2.png',
    imageUrlBack: '',
  },
  'Fiery Resolve': {
    name: 'Fiery Resolve',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-axell-florent-fotqm-t3.png',
    imageUrlBack: '',
  },
  'Assault Orders - Andrew Estermont': {
    name: 'Assault Orders - Andrew Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-andrew-estermont-fotkm-t1.png',
    imageUrlBack: '',
  },
  'Reckless Fury': {
    name: 'Reckless Fury',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-andrew-estermont-fotkm-t2.png',
    imageUrlBack: '',
  },
  'Rush of Aggression - Andrew Estermont': {
    name: 'Rush of Aggression - Andrew Estermont',
    type: CardTypes.TacticsCard,
    imageUrl: 'https://onthetablegaming.com/asoiaf-builder-images/asoiafbuilder2021/hb-andrew-estermont-fotkm-t3.png',
    imageUrlBack: '',
  },
};

export default cardData;
